import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32)),
                ('issue', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['project__name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalComplianceDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=256)),
                ('signature_panel', models.JSONField(blank=True, default=list)),
                ('tech_doc_no', models.CharField(blank=True, max_length=64, null=True)),
                ('tech_doc_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_tech_doc_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('tech_doc_no_2', models.CharField(blank=True, max_length=64, null=True)),
                ('tech_doc_issue_2', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_tech_doc_issue_2', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible', models.CharField(blank=True, max_length=64, null=True)),
                ('cat', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('not_retained', 'Not Retained'), ('retained', 'Retained')], max_length=12, null=True)),
                ('moc', models.CharField(blank=True, max_length=1, null=True)),
                ('mom_no', models.CharField(blank=True, max_length=128, null=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('to_be_issued', 'To be Issued'), ('airworthiness_review', 'Airworthiness Review'), ('to_be_re-submitted', 'To be Re-Submitted'), ('to_be_updated', 'To be Updated'), ('authority_review', 'Authority Review'), ('authority_approved', 'Authority Approved'), ('unknown', 'Unknown')], db_index=True, default='unknown', editable=False, max_length=32)),
                ('ubm_target_date', models.DateField(blank=True, db_index=True, editable=False, null=True)),
                ('ubm_delivery_date', models.DateField(blank=True, db_index=True, editable=False, null=True)),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_action_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.CharField(blank=True, max_length=255)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical compliance document',
                'verbose_name_plural': 'historical compliance documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCoverPage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('number', models.CharField(max_length=32)),
                ('issue', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical cover page',
                'verbose_name_plural': 'historical cover pages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentPurgeAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(editable=False, unique=True)),
                ('document_version', models.PositiveBigIntegerField(editable=False)),
                ('purged_by_username', models.CharField(max_length=150)),
                ('reason', models.CharField(max_length=255)),
                ('purged_at', models.DateTimeField(auto_now_add=True)),
                ('purged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_document_purge_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purged_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_size', models.PositiveBigIntegerField(default=0)),
                ('source_sha256', models.CharField(editable=False, max_length=64)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('header_row', models.PositiveSmallIntegerField(null=True)),
                ('mapped_columns', models.JSONField(default=list)),
                ('unmapped_columns', models.JSONField(default=list)),
                ('missing_columns', models.JSONField(default=list)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('duration_ms', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=32)),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('recipient_count', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('event_rules', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('change_note', models.CharField(max_length=255)),
                ('updated_by_username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('review', 'Review'), ('approval', 'Approval')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('assignee_username', models.CharField(max_length=150)),
                ('requested_by_username', models.CharField(max_length=150)),
                ('decided_by_username', models.CharField(blank=True, max_length=150)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('request_note', models.CharField(max_length=500)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('source_version', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responsible_mode', models.CharField(choices=[('automatic', 'Automatic from panel'), ('custom', 'Custom selection')], default='automatic', max_length=16)),
                ('notification_enabled', models.BooleanField(default=False)),
                ('notification_events', models.JSONField(blank=True, default=list)),
                ('docproof_issue', models.CharField(blank=True, max_length=32)),
                ('docproof_status', models.CharField(default='never_checked', max_length=32)),
                ('docproof_checked_at', models.DateTimeField(blank=True, null=True)),
                ('notification_checked_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('to_be_issued', 'To be Issued'), ('airworthiness_review', 'Airworthiness Review'), ('to_be_re-submitted', 'To be Re-Submitted'), ('to_be_updated', 'To be Updated'), ('authority_review', 'Authority Review'), ('authority_approved', 'Authority Approved'), ('unknown', 'Unknown')], max_length=32)),
                ('effective_date', models.DateField()),
                ('next_action_due_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('system', 'System')], max_length=16)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sequence'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('signature_panel', models.JSONField(blank=True, default=list)),
                ('tech_doc_no', models.CharField(blank=True, max_length=64, null=True)),
                ('tech_doc_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_tech_doc_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('tech_doc_no_2', models.CharField(blank=True, max_length=64, null=True)),
                ('tech_doc_issue_2', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_tech_doc_issue_2', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible', models.CharField(blank=True, max_length=64, null=True)),
                ('cat', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('not_retained', 'Not Retained'), ('retained', 'Retained')], max_length=12, null=True)),
                ('moc', models.CharField(blank=True, max_length=1, null=True)),
                ('mom_no', models.CharField(blank=True, max_length=128, null=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('to_be_issued', 'To be Issued'), ('airworthiness_review', 'Airworthiness Review'), ('to_be_re-submitted', 'To be Re-Submitted'), ('to_be_updated', 'To be Updated'), ('authority_review', 'Authority Review'), ('authority_approved', 'Authority Approved'), ('unknown', 'Unknown')], db_index=True, default='unknown', editable=False, max_length=32)),
                ('ubm_target_date', models.DateField(blank=True, db_index=True, editable=False, null=True)),
                ('ubm_delivery_date', models.DateField(blank=True, db_index=True, editable=False, null=True)),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_action_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.CharField(blank=True, max_length=255)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_compliance_documents', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_compliance_documents', to=settings.AUTH_USER_MODEL)),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_compliance_documents', to='auth.group')),
            ],
            options={
                'ordering': ['-created_at', 'name', 'id'],
            },
        ),
    ]
