# Generated by Django 5.2.15 on 2026-09-06 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_doors_import_mapping'),
        ('jobs', '0001_initial'),
        ('orgs', '0002_seed_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPageNumberAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_operation_id', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('document_snapshot', models.JSONField()),
                ('format_code', models.CharField(max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('credential_fingerprint', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('allocated', 'Allocated'), ('use_pending', 'Use pending'), ('completed', 'Completed'), ('reconciliation_required', 'Reconciliation required')], db_index=True, default='requested', max_length=32)),
                ('remote_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remote_number', models.CharField(blank=True, max_length=200)),
                ('remote_status', models.CharField(blank=True, max_length=20)),
                ('remote_request_id', models.CharField(blank=True, max_length=128)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cover_page_number_allocations', to=settings.AUTH_USER_MODEL)),
                ('cover_page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='number_allocation', to='compliance.coverpage')),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_page_number_allocations', to='jobs.job')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cover_page_number_allocation', to='compliance.compliancedocument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cover_page_number_allocations', to='orgs.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status', 'updated_at'], name='compliance__project_dea61c_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'actor', 'client_operation_id'), name='compliance_unique_cover_allocation_request')],
            },
        ),
    ]
