# Generated by Django 5.2.15 on 2026-09-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0006_coverpagenumberallocation"),
        ("orgs", "0002_seed_projects"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coverpage",
            name="compliance_unique_project_cover_page",
        ),
        migrations.AlterField(
            model_name="coverpage",
            name="number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="historicalcoverpage",
            name="number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name="coverpage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("project", "number"),
                name="compliance_unique_project_cover_page",
            ),
        ),
    ]
