# Generated by Django 5.2.15 on 2026-09-15 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_notificationlog_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperResetState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('generation', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='compliance_reset_singleton')],
            },
        ),
    ]
