# Generated by Django 5.2.15 on 2026-09-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_developerresetstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='cat',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompliancedocument',
            name='cat',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
