# Generated by Django 5.2.15 on 2026-09-29 12:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_alter_compliancedocument_cat_and_more'),
        ('orgs', '0004_seed_dcc_project_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='status',
            field=models.CharField(db_index=True, default='unknown', editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalcompliancedocument',
            name='status',
            field=models.CharField(db_index=True, default='unknown', editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='previous_status',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_statuses', to='orgs.project')),
            ],
            options={
                'ordering': ['label', 'value'],
                'constraints': [models.UniqueConstraint(fields=('project', 'value'), name='compliance_unique_project_status')],
            },
        ),
    ]
