# Generated by Django 5.2.15 on 2026-09-29 12:30

from django.db import migrations


def seed_statuses(apps, schema_editor):
    Project = apps.get_model("orgs", "Project")
    Document = apps.get_model("compliance", "ComplianceDocument")
    Status = apps.get_model("compliance", "DocumentStatus")
    alias = schema_editor.connection.alias
    for project_id in Project.objects.using(alias).values_list("pk", flat=True).iterator():
        values = set(Document.objects.using(alias).filter(project_id=project_id).values_list("status", flat=True))
        values.add("unknown")
        for value in sorted(values):
            Status.objects.using(alias).get_or_create(
                project_id=project_id, value=value,
                defaults={"label": value.replace("_", " ").title()},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_project_status_catalog'),
    ]

    operations = [migrations.RunPython(seed_statuses)]
