# Generated by Django 5.2.15 on 2026-09-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_seed_project_statuses'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compliancedocument',
            name='compliance_unique_cover_page_tech_doc',
        ),
        migrations.AlterField(
            model_name='coverpage',
            name='number',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalcoverpage',
            name='number',
            field=models.CharField(max_length=32),
        ),
    ]
