# Generated by Django 5.2.15 on 2026-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_require_document_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedocument',
            name='ubm_revised_target_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompliancedocument',
            name='ubm_revised_target_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='ubm_delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='ubm_target_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompliancedocument',
            name='ubm_delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompliancedocument',
            name='ubm_target_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
