# Generated by Django 5.2.15 on 2026-08-17 21:28

import automations.models
import django.db.models.deletion
import jobs.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('orgs', '0002_seed_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcrWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_pdf', models.FileField(max_length=500, storage=jobs.storage.PrivateJobStorage(), upload_to=automations.models.ecr_source_path)),
                ('source_sha256', models.CharField(max_length=64)),
                ('create_idempotency_key', models.CharField(blank=True, max_length=128)),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('review', 'Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reconciliation_required', 'Reconciliation required')], default='review', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('project_key', models.CharField(blank=True, max_length=20)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('selected_subtasks', models.JSONField(blank=True, default=list)),
                ('marker_label', models.CharField(editable=False, max_length=64, unique=True)),
                ('jira_issue_key', models.CharField(blank=True, max_length=64)),
                ('publication_state', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('publish_started_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ecr_workflows', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecr_workflows', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='ecr_workflows', to='orgs.project')),
                ('publication_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecr_publication_workflow', to='jobs.job')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EcrWorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('version', models.PositiveIntegerField()),
                ('code', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='automations.ecrworkflow')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ecrworkflow',
            index=models.Index(fields=['owner', 'status', 'updated_at'], name='automations_owner_i_66711d_idx'),
        ),
        migrations.AddConstraint(
            model_name='ecrworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('create_idempotency_key', ''), _negated=True), fields=('owner', 'create_idempotency_key'), name='automations_unique_owner_ecr_create_key'),
        ),
    ]
