# Generated by Django 5.2 on 2025-09-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasoj', '0002_panel_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='title',
            field=models.CharField(max_length=255, choices=[('AS', 'AS'), ('CVE', 'CVE'), ('IPT', 'IPT'), ('SSB', 'SSB'), ('Air Force', 'Air Force'), ('PSK', 'PSK'), ('PCE', 'PCE')]),
        ),
    ]
