# Generated by Django 5.2 on 2025-09-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasoj', '0003_alter_responsible_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='discipline',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
    ]
