# Generated by Django 5.2.15 on 2026-07-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasoj', '0018_compdoc_cover_page_historicalcompdoc_cover_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compdoc',
            name='status',
            field=models.CharField(choices=[('to_be_issued', 'To be Issued'), ('airworthiness_review', 'Airworthiness Review'), ('to_be_re-submitted', 'To be Re-Submitted'), ('to_be_updated', 'To be Updated'), ('authority_review', 'Authority Review'), ('authority_approved', 'Authority Approved'), ('unknown', 'Unknown')], db_index=True, default='unknown', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='compdoc',
            name='ubm_delivery_date',
            field=models.DateField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='compdoc',
            name='ubm_target_date',
            field=models.DateField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompdoc',
            name='status',
            field=models.CharField(choices=[('to_be_issued', 'To be Issued'), ('airworthiness_review', 'Airworthiness Review'), ('to_be_re-submitted', 'To be Re-Submitted'), ('to_be_updated', 'To be Updated'), ('authority_review', 'Authority Review'), ('authority_approved', 'Authority Approved'), ('unknown', 'Unknown')], db_index=True, default='unknown', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='historicalcompdoc',
            name='ubm_delivery_date',
            field=models.DateField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompdoc',
            name='ubm_target_date',
            field=models.DateField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
