# Generated by Django 5.2.15 on 2026-08-11 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('orgs', '0002_seed_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssueDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_key', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=30000)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('reconciliation_required', 'Reconciliation required')], default='draft', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('marker_label', models.CharField(editable=False, max_length=64, unique=True)),
                ('jira_issue_key', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('publish_started_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jira_issue_drafts', to=settings.AUTH_USER_MODEL)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_jira_issue_drafts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issue_drafts', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='jira_issue_drafts', to='orgs.project')),
                ('publication_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jira_publication_draft', to='jobs.job')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_jira_issue_drafts', to=settings.AUTH_USER_MODEL)),
                ('source_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issue_draft', to='jobs.job')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JiraIssueDraftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dcc.jiraissuedraft')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DccRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_dcc_records', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcc_records', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='dcc_records', to='orgs.project')),
            ],
            options={
                'ordering': ['-updated_at', 'issue', 'id'],
                'indexes': [models.Index(fields=['owner', 'active', 'updated_at'], name='dcc_dccreco_owner_i_e7e434_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='jiraissuedraft',
            index=models.Index(fields=['owner', 'status', 'updated_at'], name='dcc_jiraiss_owner_i_aa1385_idx'),
        ),
    ]
