# Generated by Django 5.2 on 2025-05-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_dcc',
            name='dcc_path',
            field=models.FileField(upload_to='deneme'),
        ),
    ]
