# Generated by Django 5.2.15 on 2026-09-03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DccReminderDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("message_id", models.CharField(max_length=255, unique=True)),
                ("subject", models.CharField(max_length=998)),
                ("context", models.JSONField(default=dict)),
                ("recipients", models.JSONField(default=list)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("claimed", "Claimed"), ("sent", "Sent"), ("failed", "Failed")], default="pending", max_length=16)),
                ("recipient_count", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("lease_token", models.UUIDField(blank=True, editable=False, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("claim_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("record", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reminder_deliveries", to="dcc.dccrecord")),
                ("requested_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dcc_reminder_deliveries", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [models.Index(fields=["status", "next_attempt_at"], name="dcc_dccremi_status_18372b_idx")],
                "constraints": [models.UniqueConstraint(condition=models.Q(("requested_by__isnull", False)), fields=("requested_by", "idempotency_key"), name="dcc_unique_reminder_idempotency")],
            },
        ),
    ]
