# Generated by Django 5.2 on 2025-05-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0002_alter_jira_dcc_dcc_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_dcc',
            name='dcc_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jira_dcc',
            name='issue',
            field=models.TextField(),
        ),
    ]
