# Generated by Django 5.2 on 2025-05-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0003_alter_jira_dcc_dcc_path_alter_jira_dcc_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_dcc',
            name='dcc_path',
            field=models.CharField(max_length=255, ),
        ),
        migrations.AlterField(
            model_name='jira_dcc',
            name='issue',
            field=models.CharField(max_length=255, ),
        ),
    ]
