# Generated by Django 5.2 on 2025-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0004_alter_jira_dcc_dcc_path_alter_jira_dcc_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_dcc',
            name='active',
            field=models.BooleanField(help_text='If it is active, then it will check the issue on JIRA'),
        ),
        migrations.AlterField(
            model_name='jira_dcc',
            name='dcc_path',
            field=models.CharField(max_length=512, verbose_name='DCC Folder Path'),
        ),
    ]
