# Generated by Django 5.2 on 2025-05-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0005_alter_jira_dcc_active_alter_jira_dcc_dcc_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_dcc',
            name='dcc_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='DCC Folder Path'),
        ),
    ]
