# Generated by Django 5.2 on 2025-05-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0006_alter_jira_dcc_dcc_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='jira_dcc',
            name='ecd_name',
            field=models.CharField(max_length=255, default=123),
            preserve_default=False,
        ),
    ]
