# Generated by Django 5.2 on 2025-06-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0008_jira_dcc_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_dcc',
            name='issue',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
