# Generated by Django 5.2 on 2025-06-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0009_alter_jira_dcc_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_dcc',
            name='issue',
            field=models.CharField(max_length=255, ),
        ),
    ]
