# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0012_jira_dcc_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jira_dcc',
            name='last_reminder_mail_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
