# Generated by Django 5.2.15 on 2026-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcc", "0013_jira_dcc_last_reminder_mail_sent_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jira_dcc",
            options={"ordering": ["-created_time", "issue", "id"]},
        ),
    ]
