# Generated by Django 5.2.15 on 2026-07-19 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0015_jiraissuedraft_jiraissuedraftevent_and_more'),
        ('jobs', '0009_alter_job_retry_of_job_jobs_unique_direct_retry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraissuedraft',
            name='source_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issue_draft', to='jobs.job'),
        ),
    ]
