# Generated by Django 5.2.15 on 2026-07-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0016_alter_jiraissuedraft_source_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissuedraft',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
