# Generated by Django 5.2.15 on 2026-07-20 18:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0017_jiraissuedraft_extra_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DccCompdocTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(db_index=True)),
                ('job_input_sha256', models.CharField(db_index=True, max_length=64)),
                ('issue_key', models.CharField(max_length=64)),
                ('project_slug', models.CharField(max_length=64)),
                ('compdoc_id', models.UUIDField()),
                ('source_history_id', models.BigIntegerField(null=True)),
                ('source_history_at', models.DateTimeField(null=True)),
                ('snapshot_fingerprint', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dcc_compdoc_traces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confirmed_at', 'issue_key', 'id'],
                'indexes': [models.Index(fields=['project_slug', 'compdoc_id', 'confirmed_at'], name='dcc_compdoc_history_idx'), models.Index(fields=['confirmed_by', 'job_input_sha256'], name='dcc_trace_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('job_id', 'project_slug', 'compdoc_id'), name='dcc_unique_job_compdoc_trace')],
            },
        ),
    ]
