# Generated by Django 5.2.15 on 2026-07-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0018_dcccompdoctrace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DccCompdocTrace',
        ),
    ]
