# Generated by Django 5.2 on 2025-10-21 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pptx/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converting', 'Converting'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='slides/')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='slides/thumbs/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='pptxgallery.presentation')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('presentation', 'index')},
            },
        ),
    ]
