# Generated by Django 5.2.15 on 2026-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pptxgallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="presentation",
            options={"ordering": ["-created_at", "title", "id"]},
        ),
    ]
