from django.urls import path

from .api import (
    ActivityView,
    ArchiveView,
    DashboardView,
    DocumentCollectionView,
    DocumentDetailView,
    DocumentFieldsView,
    DocumentHistoryView,
    DocProofRefreshView,
    DoorsImportConfirmView,
    DoorsImportPreviewView,
    DoorsImportSourceView,
    ExportView,
    ImportAuditCollectionView,
    ImportAuditDetailView,
    ImportConfirmView,
    ImportPreviewView,
    NotificationPolicyView,
    RestoreView,
    ReviewCollectionView,
    ReviewDecisionView,
    TrackingView,
    TransitionView,
    WorkView,
)


urlpatterns = [
    path("", DocumentCollectionView.as_view(), name="compliance-document-list"),
    path("fields/", DocumentFieldsView.as_view(), name="compliance-document-fields"),
    path("dashboard/", DashboardView.as_view(), name="compliance-dashboard"),
    path("notification-policy/", NotificationPolicyView.as_view(), name="compliance-notification-policy"),
    path("export/", ExportView.as_view(), name="compliance-export"),
    path("imports/preview/", ImportPreviewView.as_view(), name="compliance-import-preview"),
    path("imports/confirm/", ImportConfirmView.as_view(), name="compliance-import-confirm"),
    path(
        "imports/doors/sources/<uuid:job_id>/",
        DoorsImportSourceView.as_view(),
        name="compliance-doors-import-source",
    ),
    path(
        "imports/doors/preview/",
        DoorsImportPreviewView.as_view(),
        name="compliance-doors-import-preview",
    ),
    path(
        "imports/doors/confirm/",
        DoorsImportConfirmView.as_view(),
        name="compliance-doors-import-confirm",
    ),
    path("import-audits/", ImportAuditCollectionView.as_view(), name="compliance-import-audits"),
    path("import-audits/<uuid:audit_id>/", ImportAuditDetailView.as_view(), name="compliance-import-audit"),
    path("<uuid:document_id>/", DocumentDetailView.as_view(), name="compliance-document-detail"),
    path("<uuid:document_id>/history/", DocumentHistoryView.as_view(), name="compliance-document-history"),
    path("<uuid:document_id>/activity/", ActivityView.as_view(), name="compliance-document-activity"),
    path("<uuid:document_id>/transitions/", TransitionView.as_view(), name="compliance-document-transition"),
    path("<uuid:document_id>/work/", WorkView.as_view(), name="compliance-document-work"),
    path("<uuid:document_id>/archive/", ArchiveView.as_view(), name="compliance-document-archive"),
    path("<uuid:document_id>/restore/", RestoreView.as_view(), name="compliance-document-restore"),
    path("<uuid:document_id>/tracking/", TrackingView.as_view(), name="compliance-document-tracking"),
    path(
        "<uuid:document_id>/tracking/docproof/",
        DocProofRefreshView.as_view(),
        name="compliance-document-docproof-refresh",
    ),
    path("<uuid:document_id>/reviews/", ReviewCollectionView.as_view(), name="compliance-document-reviews"),
    path("<uuid:document_id>/reviews/<uuid:review_id>/decision/", ReviewDecisionView.as_view(), name="compliance-review-decision"),
]
