# Generated by Django 5.2 on 2025-07-31 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AESACompDoc',
            fields=[
                ('compdoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.compdoc')),
                ('tech_doc_no_2', models.CharField(blank=True, max_length=32, null=True)),
                ('tech_doc_issue_2', models.IntegerField(blank=True, null=True)),
                ('delivered_tech_doc_issue_2', models.IntegerField(blank=True, null=True)),
            ],
            bases=('common.compdoc',),
        ),
    ]
