# Generated by Django 5.2 on 2025-08-19 11:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesa', '0004_compdoc_history_delete_historicalcompdoc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compdoc',
            name='history',
        ),
        migrations.CreateModel(
            name='HistoricalCompDoc',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('panel', models.CharField(blank=True, max_length=128, null=True)),
                ('signature_panel', models.CharField(blank=True, max_length=128, null=True)),
                ('ata', models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Ata chapter must consist of four digits.')])),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('cover_page_no', models.CharField(blank=True, max_length=32, null=True)),
                ('cover_page_issue', models.IntegerField(blank=True, null=True)),
                ('tech_doc_no', models.CharField(blank=True, max_length=64, null=True)),
                ('tech_doc_issue', models.IntegerField(blank=True, null=True)),
                ('delivered_tech_doc_issue', models.IntegerField(blank=True, null=True)),
                ('responsible', models.CharField(blank=True, max_length=64, null=True)),
                ('loi', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('not_retained', 'Not Retained'), ('retained', 'Retained')], max_length=12, null=True)),
                ('moc', models.CharField(blank=True, max_length=1, null=True)),
                ('requirements', models.JSONField(default=list)),
                ('status_flow', models.JSONField(default=list)),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tech_doc_no_2', models.CharField(blank=True, max_length=32, null=True)),
                ('tech_doc_issue_2', models.IntegerField(blank=True, null=True)),
                ('delivered_tech_doc_issue_2', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comp doc',
                'verbose_name_plural': 'historical comp docs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
