# Generated by Django 5.2 on 2025-09-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesa', '0007_panel_orgperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, )),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255, choices=[('AS', 'AS'), ('CVE', 'CVE'), ('PSK', 'PSK'), ('IPT', 'IPT'), ('SSB', 'SSB'), ('Air Force', 'Air Force')])),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='aesa.panel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OrgPerson',
        ),
    ]
