# Generated by Django 5.2 on 2025-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesa', '0009_alter_responsible_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='title',
            field=models.CharField(max_length=255, choices=[('as', 'AS'), ('cve', 'CVE'), ('psk', 'PSK'), ('ipt', 'IPT'), ('ssb', 'SSB'), ('air force', 'Air Force')]),
        ),
    ]
