# Generated by Django 5.2 on 2025-09-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesa', '0010_alter_responsible_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='title',
            field=models.CharField(max_length=255, choices=[('AS', 'AS'), ('CVE', 'CVE'), ('PSK', 'PSK'), ('IPT', 'IPT'), ('SSB', 'SSB'), ('Air Force', 'Air Force')]),
        ),
    ]
