# Generated by Django 5.2 on 2025-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesa', '0016_alter_compdoc_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdoc',
            name='delivered_tech_doc_issue_2',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='tech_doc_issue_2',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='tech_doc_no_2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='delivered_tech_doc_issue_2',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='tech_doc_issue_2',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='tech_doc_no_2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
