# Generated by Django 5.2 on 2025-12-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesa', '0020_alter_responsible_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compdoc',
            old_name='loi',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='historicalcompdoc',
            old_name='loi',
            new_name='cat',
        ),
    ]
