# Generated by Django 5.2.15 on 2026-07-21 21:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


def link_cover_pages(apps, schema_editor):
    """Link existing Aesa compliance documents to shared cover pages."""

    cover_page_model = apps.get_model('common', 'CoverPage')
    models_to_link = (apps.get_model('aesa', 'CompDoc'), apps.get_model('aesa', 'HistoricalCompDoc'))
    for model in models_to_link:
        for document in model.objects.order_by('cover_page_no').iterator():
            cover_page, _ = cover_page_model.objects.get_or_create(
                project_slug='aesa', number=document.cover_page_no,
                defaults={'issue': document.cover_page_issue},
            )
            document.cover_page_id = cover_page.pk
            document.save(update_fields=['cover_page'])


class Migration(migrations.Migration):

    dependencies = [
        ('aesa', '0027_alter_compdoc_options_alter_panel_options_and_more'),
        ('common', '0011_coverpage_historicalcoverpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='compdoc',
            name='cover_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_compliance_documents', to='common.coverpage'),
        ),
        migrations.AddField(
            model_name='historicalcompdoc',
            name='cover_page',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.coverpage'),
        ),
        migrations.RunPython(link_cover_pages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='compdoc',
            name='cover_page',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_compliance_documents', to='common.coverpage'),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='cover_page_no',
            field=models.CharField(default=uuid.uuid4, max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='cover_page_no',
            field=models.CharField(default=uuid.uuid4, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='compdoc',
            constraint=models.UniqueConstraint(fields=('cover_page', 'name'), name='aesa_unique_cover_page_compdoc'),
        ),
    ]
