# Generated by Django 5.2.15 on 2026-07-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesa', '0030_compdoc_archive_reason_compdoc_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdoc',
            name='cover_page_issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='delivered_tech_doc_issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='delivered_tech_doc_issue_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='tech_doc_issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='tech_doc_issue_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='cover_page_issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='delivered_tech_doc_issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='delivered_tech_doc_issue_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='tech_doc_issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='tech_doc_issue_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='discipline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='title',
            field=models.CharField(choices=[('AS', 'AS'), ('CVE', 'CVE'), ('IPT', 'IPT'), ('SSB', 'SSB'), ('Air Force', 'Air Force'), ('PSK', 'PSK'), ('PCE', 'PCE')], max_length=32),
        ),
    ]
