# Generated by Django 5.2 on 2025-07-31 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzgurCompDoc',
            fields=[
                ('compdoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.compdoc')),
            ],
            bases=('common.compdoc',),
        ),
    ]
