# Generated by Django 5.2 on 2025-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozgur', '0003_historicalcompdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='compdoc',
            name='history',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalCompDoc',
        ),
    ]
