# Generated by Django 5.2 on 2025-09-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozgur', '0005_remove_compdoc_history_historicalcompdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdoc',
            name='signature_panel',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='signature_panel',
            field=models.JSONField(default=list),
        ),
    ]
