# Generated by Django 5.2 on 2025-09-08 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozgur', '0006_alter_compdoc_signature_panel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, )),
                ('discipline', models.CharField(max_length=255, )),
                ('ata', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Ata chapter must consist of four digits.')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, )),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255, choices=[('AS', 'AS'), ('CVE', 'CVE'), ('IPT', 'IPT'), ('SSB', 'SSB'), ('Air Force', 'Air Force'), ('PSK', 'PSK'), ('PCE', 'PCE')])),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='ozgur.panel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
