# Generated by Django 5.2 on 2025-10-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozgur', '0010_alter_compdoc_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdoc',
            name='mom_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='mom_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
