# Generated by Django 5.2 on 2025-12-12 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozgur', '0017_alter_panel_ata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdoc',
            name='cover_page_no',
            field=models.CharField(default=uuid.uuid4, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='cover_page_no',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
