# Generated by Django 5.2.15 on 2026-07-29 20:52

import django.db.models.deletion
from django.db import migrations, models


def link_responsibles(apps, schema_editor):
    people_model = apps.get_model("orgs", "People")
    responsible_model = apps.get_model("ozgur", "Responsible")
    for responsible in responsible_model.objects.iterator():
        person, _created = people_model.objects.get_or_create(
            person_id=responsible.person_id,
            defaults={"name": responsible.name, "email": responsible.email},
        )
        responsible_model.objects.filter(pk=responsible.pk).update(directory_person=person)


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_responsible_directory_person'),
        ('ozgur', '0024_alter_compdoc_cover_page_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='directory_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_responsible_assignments', to='orgs.people'),
        ),
        migrations.RunPython(link_responsibles, migrations.RunPython.noop),
    ]
