# Generated by Django 5.2 on 2025-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok30', '0005_alter_compdoc_mom_no_alter_historicalcompdoc_mom_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='person_id',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
