# Generated by Django 5.2 on 2025-12-10 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok30', '0008_rename_loi_compdoc_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdoc',
            name='ata',
            field=models.CharField(default='00-00', max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{2}$', message='Ata chapter must consist of four digits (XX-XX).')]),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='ata',
            field=models.CharField(default='00-00', max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{2}$', message='Ata chapter must consist of four digits (XX-XX).')]),
        ),
    ]
