# Generated by Django 5.2 on 2025-12-10 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok30', '0009_alter_compdoc_ata_alter_historicalcompdoc_ata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='ata',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{2}$', message='Ata chapter must consist of four digits (XX-XX).')]),
        ),
    ]
