# Generated by Django 5.2 on 2025-12-12 13:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel', models.CharField(blank=True, max_length=128, null=True)),
                ('signature_panel', models.JSONField(blank=True, default=list, null=True)),
                ('ata', models.CharField(default='00-00', max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{2}$', message='Ata chapter must consist of four digits (XX-XX).')])),
                ('name', models.CharField(max_length=256)),
                ('cover_page_no', models.CharField(default=uuid.uuid4, max_length=32, unique=True)),
                ('cover_page_issue', models.CharField(max_length=255, blank=True, null=True)),
                ('tech_doc_no', models.CharField(blank=True, max_length=64, null=True)),
                ('tech_doc_issue', models.CharField(max_length=255, blank=True, null=True)),
                ('delivered_tech_doc_issue', models.CharField(max_length=255, blank=True, null=True)),
                ('responsible', models.CharField(blank=True, max_length=64, null=True)),
                ('cat', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('not_retained', 'Not Retained'), ('retained', 'Retained')], max_length=12, null=True)),
                ('moc', models.CharField(blank=True, max_length=1, null=True)),
                ('mom_no', models.CharField(blank=True, max_length=128, null=True)),
                ('requirements', models.JSONField(blank=True, default=list, null=True)),
                ('status_flow', models.JSONField(blank=True, default=list, null=True)),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tech_doc_no_2', models.CharField(blank=True, max_length=64, null=True)),
                ('tech_doc_issue_2', models.CharField(max_length=255, blank=True, null=True)),
                ('delivered_tech_doc_issue_2', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, )),
                ('discipline', models.CharField(max_length=255, )),
                ('ata', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{2}$', message='Ata chapter must consist of four digits (XX-XX).')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCompDoc',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('panel', models.CharField(blank=True, max_length=128, null=True)),
                ('signature_panel', models.JSONField(blank=True, default=list, null=True)),
                ('ata', models.CharField(default='00-00', max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{2}$', message='Ata chapter must consist of four digits (XX-XX).')])),
                ('name', models.CharField(max_length=256)),
                ('cover_page_no', models.CharField(db_index=True, default=uuid.uuid4, max_length=32)),
                ('cover_page_issue', models.CharField(max_length=255, blank=True, null=True)),
                ('tech_doc_no', models.CharField(blank=True, max_length=64, null=True)),
                ('tech_doc_issue', models.CharField(max_length=255, blank=True, null=True)),
                ('delivered_tech_doc_issue', models.CharField(max_length=255, blank=True, null=True)),
                ('responsible', models.CharField(blank=True, max_length=64, null=True)),
                ('cat', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('not_retained', 'Not Retained'), ('retained', 'Retained')], max_length=12, null=True)),
                ('moc', models.CharField(blank=True, max_length=1, null=True)),
                ('mom_no', models.CharField(blank=True, max_length=128, null=True)),
                ('requirements', models.JSONField(blank=True, default=list, null=True)),
                ('status_flow', models.JSONField(blank=True, default=list, null=True)),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tech_doc_no_2', models.CharField(blank=True, max_length=64, null=True)),
                ('tech_doc_issue_2', models.CharField(max_length=255, blank=True, null=True)),
                ('delivered_tech_doc_issue_2', models.CharField(max_length=255, blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comp doc',
                'verbose_name_plural': 'historical comp docs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=255, )),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255, choices=[('AS', 'AS'), ('CVE', 'CVE'), ('IPT', 'IPT'), ('SSB', 'SSB'), ('Air Force', 'Air Force'), ('PSK', 'PSK'), ('PCE', 'PCE')])),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='gokbey.panel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
