# Generated by Django 5.2 on 2025-08-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piku', '0003_compdoc_delete_pikucompdoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempCompDoc',
        ),
    ]
