# Generated by Django 5.2 on 2025-09-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piku', '0013_compdoc_mom_no_historicalcompdoc_mom_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdoc',
            name='requirements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='signature_panel',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='status_flow',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='requirements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='signature_panel',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='status_flow',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
