# Generated by Django 5.2 on 2025-11-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piku', '0016_responsible_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='person_id',
            field=models.CharField(max_length=6),
        ),
    ]
