# Generated by Django 5.2.15 on 2026-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piku', '0022_alter_compdoc_cover_page_no_alter_compdoc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdoc',
            name='cover_page_issue',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='delivered_tech_doc_issue',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='tech_doc_issue',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='cover_page_issue',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='delivered_tech_doc_issue',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='tech_doc_issue',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='discipline',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='title',
            field=models.CharField(choices=[('AS', 'AS'), ('CVE', 'CVE'), ('IPT', 'IPT'), ('SSB', 'SSB'), ('Air Force', 'Air Force'), ('PSK', 'PSK'), ('PCE', 'PCE')]),
        ),
    ]
