# Generated by Django 5.2 on 2025-08-21 09:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField()),
                ('ata', models.CharField(default='0000', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Ata chapter must consist of four digits.')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='orgs.project')),
            ],
        ),
        migrations.CreateModel(
            name='OrgPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255, choices=[('as', 'AS'), ('cve', 'CVE'), ('psk', 'PSK'), ('ipt', 'IPT'), ('ssb', 'SSB'), ('af', 'Air Force')])),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='orgs.panel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='orgs.project')),
            ],
        ),
    ]
