# Generated by Django 5.2 on 2025-08-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgperson',
            name='name',
            field=models.CharField(max_length=255, ),
        ),
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(max_length=255, ),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, ),
        ),
    ]
