# Generated by Django 5.2 on 2025-08-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_alter_orgperson_name_alter_panel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(),
        ),
    ]
