# Generated by Django 5.2 on 2025-08-25 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='ata',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Ata chapter must consist of four digits.')]),
        ),
    ]
