# Generated by Django 5.2 on 2025-08-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_alter_panel_ata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AlterField(
            model_name='orgperson',
            name='title',
            field=models.CharField(max_length=255, choices=[('AS', 'AS'), ('CVE', 'CVE'), ('PSK', 'PSK'), ('IPT', 'IPT'), ('SSB', 'SSB'), ('Air Force', 'Air Force')]),
        ),
    ]
