# Generated by Django 5.2 on 2025-09-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
