# Generated by Django 5.2 on 2025-09-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_panel_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='panel',
            constraint=models.UniqueConstraint(fields=('project', 'ata'), name='ata_chapter'),
        ),
    ]
