# Generated by Django 5.2 on 2025-09-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_panel_ata_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgperson',
            name='title',
            field=models.CharField(max_length=255, choices=[('AS', 'as'), ('CVE', 'CVE'), ('PSK', 'PSK'), ('IPT', 'IPT'), ('SSB', 'SSB'), ('Air Force', 'Air Force')]),
        ),
    ]
