# Generated by Django 5.2 on 2025-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_alter_orgperson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgperson',
            name='person_id',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
