# Generated by Django 5.2 on 2025-11-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_orgperson_person_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgPerson',
            new_name='Responsible',
        ),
    ]
