# Generated by Django 5.2 on 2025-11-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0014_rename_orgperson_responsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=255, )),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
