# Generated by Django 5.2 on 2025-11-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_alter_people_person_id_alter_responsible_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=255, db_index=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='person_id',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
