# Generated by Django 5.2 on 2025-11-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_alter_people_email_alter_people_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='person_id',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
    ]
