# Generated by Django 5.2 on 2025-12-10 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_alter_people_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='ata',
            field=models.CharField(default='00-00', max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{2}$', message='Ata chapter must consist of four digits (XX-XX).')]),
        ),
    ]
