# Generated by Django 5.2.15 on 2026-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_alter_panel_ata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='title',
            field=models.CharField(choices=[('AS', 'AS'), ('CVE', 'CVE'), ('PSK', 'PSK'), ('IPT', 'IPT'), ('SSB', 'SSB'), ('Air Force', 'Air Force')]),
        ),
    ]
