# Generated by Django 5.2.15 on 2026-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0020_alter_panel_name_alter_people_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="panel",
            options={"ordering": ["project__name", "ata", "name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="people",
            options={"ordering": ["name", "person_id"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="responsible",
            options={"ordering": ["project__name", "name", "person_id", "id"]},
        ),
    ]
