# Generated by Django 5.2.15 on 2026-07-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_alter_panel_options_alter_people_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='title',
            field=models.CharField(choices=[('AS', 'AS'), ('CVE', 'CVE'), ('PSK', 'PSK'), ('IPT', 'IPT'), ('SSB', 'SSB'), ('Air Force', 'Air Force')], max_length=32),
        ),
    ]
