"""
Django settings for awcenter project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from corsheaders.defaults import default_headers, default_methods
from django.core.exceptions import ImproperlyConfigured
import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
ENV_FILE = Path(os.environ.get("AWCENTER_ENV_FILE", BASE_DIR / ".env"))
env.read_env(ENV_FILE)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEV_SECRET_KEY = "aw-center-local-development-secret-key-change-before-production-2026"
SECRET_KEY = env.str("SECRET_KEY", default="")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = DEV_SECRET_KEY
    else:
        raise ImproperlyConfigured("SECRET_KEY must be defined when DEBUG is False.")

IPV4_ADDRESS = env.str("IPV4_ADDRESS")
PORT = env.int("PORT")

DOCPROOF_URL = env.str("DOCPROOF_URL")
DOORS_EXECUTABLE = env.str("DOORS_EXECUTABLE")
DOORS_DATABASE = env.str("DOORS_DATABASE", default="")
DOORS_OLE_PROG_ID = env.str("DOORS_OLE_PROG_ID", default="DOORS.Application")
DOORS_PREFER_ACTIVE_INSTANCE = env.bool("DOORS_PREFER_ACTIVE_INSTANCE", default=True)
DOORS_AUTO_START_CLIENT = env.bool("DOORS_AUTO_START_CLIENT", default=False)
DOORS_STARTUP_TIMEOUT_SECONDS = env.float("DOORS_STARTUP_TIMEOUT_SECONDS", default=30.0)
DOORS_RUN_TIMEOUT_SECONDS = env.float("DOORS_RUN_TIMEOUT_SECONDS", default=120.0)
DOORS_MAX_RESULT_BYTES = env.int("DOORS_MAX_RESULT_BYTES", default=10 * 1024 * 1024)

TEAMCENTER_BASE_URL = env.str("TEAMCENTER_BASE_URL", default="")
TEAMCENTER_SERVICE_ROOT = env.str("TEAMCENTER_SERVICE_ROOT", default="RestServices")
TEAMCENTER_AUTH_MODE = env.str("TEAMCENTER_AUTH_MODE", default="password")
TEAMCENTER_USERNAME = env.str("TEAMCENTER_USERNAME", default="")
TEAMCENTER_PASSWORD = env.str("TEAMCENTER_PASSWORD", default="")
TEAMCENTER_GROUP = env.str("TEAMCENTER_GROUP", default="")
TEAMCENTER_ROLE = env.str("TEAMCENTER_ROLE", default="")
TEAMCENTER_VERIFY_SSL = env.str("TEAMCENTER_VERIFY_SSL", default="true")
TEAMCENTER_JSESSIONID = env.str("TEAMCENTER_JSESSIONID", default="")
TEAMCENTER_XSRF_TOKEN = env.str("TEAMCENTER_XSRF_TOKEN", default="")
TEAMCENTER_CONNECT_TIMEOUT_SECONDS = env.float("TEAMCENTER_CONNECT_TIMEOUT_SECONDS", default=10.0)
TEAMCENTER_READ_TIMEOUT_SECONDS = env.float("TEAMCENTER_READ_TIMEOUT_SECONDS", default=60.0)
TEAMCENTER_MAX_READ_RETRIES = env.int("TEAMCENTER_MAX_READ_RETRIES", default=2)
TEAMCENTER_MAX_RESPONSE_BYTES = env.int("TEAMCENTER_MAX_RESPONSE_BYTES", default=10 * 1024 * 1024)

JIRA_LEGACY_URL = env.str("JIRA_LEGACY_URL")
JIRA_BTB_URL = env.str("JIRA_BTB_URL")

AW_USERNAME = env.str("AW_USERNAME", "")
AW_PASSWORD = env.str("AW_PASSWORD", "")
FFMPEG_EXECUTABLE = env.str("FFMPEG_EXECUTABLE", default="ffmpeg")


def get_default_auth_cookie_samesite(debug):
    """Return the safe default SameSite policy for the runtime mode."""
    return "Lax" if debug else "None"


def get_default_auth_cookie_secure(debug):
    """Return whether auth cookies should default to Secure for the runtime mode."""
    return not debug


CERTIFICATES_DIR = BASE_DIR / "certificates"
CUSTOM_TEMPLATE_DIR = BASE_DIR / "custom_templates"
REPOSITORY_DIR = BASE_DIR.parent
FRONTEND_DIST_DIR = Path(env.path("FRONTEND_DIST_DIR", default=REPOSITORY_DIR / "frontend" / "dist"))
FRONTEND_ASSETS_DIR = FRONTEND_DIST_DIR / "assets"

FRONTEND_RESET_URL = env.str(
    "FRONTEND_RESET_URL",
    default=f"http{'s' if not DEBUG else ''}://{IPV4_ADDRESS if not DEBUG else 'localhost'}:{PORT if not DEBUG else 5173}/app/login"
)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[
    IPV4_ADDRESS, "127.0.0.1", "localhost"
])

# Application definition

INSTALLED_APPS = [
    'awcenter.admin.AwCenterAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'simple_history',
    'users',
    'common',
    'projects.ozgur',
    'projects.piku',
    'projects.aesa',
    'projects.hys',
    'projects.blok30',
    'projects.blok4050',
    'projects.havasoj',
    'projects.gokbey',
    'dcc',
    'doors',
    'teamcenter',
    'ddf',
    'orgs',
    'pptxgallery',
    'outlook',
    'releases',
    'media_tools',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'awcenter.api_errors.ApiErrorContractMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

if not DEBUG:
    MIDDLEWARE += ['awcenter.middleware.RequestUserLogMiddleware']

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = []
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
    if not CORS_ALLOWED_ORIGINS:
        raise ImproperlyConfigured("CORS_ALLOWED_ORIGINS must be set when DEBUG is False.")

CORS_ALLOW_HEADERS = list(default_headers)
CORS_ALLOW_METHODS = list(default_methods)
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Browser authentication strategy:
# - The SPA uses a DRF token stored in an HttpOnly auth cookie.
# - Header tokens remain supported for non-browser clients and DEBUG fallback.
# - Unsafe cookie-authenticated requests are protected by Django CSRF checks.
#
# Cross-site deployments must use HTTPS, AUTH_COOKIE_SAMESITE=None,
# AUTH_COOKIE_SECURE=True, CORS_ALLOWED_ORIGINS, and CSRF_TRUSTED_ORIGINS.
# Same-site deployments should prefer AUTH_COOKIE_SAMESITE=Lax.
AUTH_COOKIE_NAME = env.str("AUTH_COOKIE_NAME", default="auth_token")
AUTH_COOKIE_MAX_AGE = env.int("AUTH_COOKIE_MAX_AGE", default=60 * 60 * 24 * 14)
AUTH_COOKIE_DEFAULT_SAMESITE = get_default_auth_cookie_samesite(DEBUG)
AUTH_COOKIE_SAMESITE = env.str("AUTH_COOKIE_SAMESITE", default=AUTH_COOKIE_DEFAULT_SAMESITE)
AUTH_COOKIE_SECURE = env.bool("AUTH_COOKIE_SECURE", default=get_default_auth_cookie_secure(DEBUG))
AUTH_TOKEN_RESPONSE_ENABLED = env.bool("AUTH_TOKEN_RESPONSE_ENABLED", default=DEBUG)

ROOT_URLCONF = 'awcenter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            FRONTEND_DIST_DIR,
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'awcenter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
    "db_old": env.db("DB_OLD_URL", default=f"sqlite:///{BASE_DIR / 'db_old.sqlite3'}"),
}
DATABASES["default"]["CONN_MAX_AGE"] = env.int("DATABASE_CONN_MAX_AGE", default=60)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True
USE_TZ = True

DATE_INPUT_FORMATS = ['%d.%m.%Y', '%d/%m/%Y', '%Y-%m-%d']
DATETIME_INPUT_FORMATS = ['%d.%m.%Y %H:%M']
DATE_FORMAT = 'd.m.Y'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/core/'
STATIC_ROOT = Path(env.path('STATIC_ROOT', default=BASE_DIR / 'static'))
STATICFILES_DIRS = [BASE_DIR / 'core']
if FRONTEND_ASSETS_DIR.exists():
    STATICFILES_DIRS.append(('assets', FRONTEND_ASSETS_DIR))
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = Path(env.path('MEDIA_ROOT', default=BASE_DIR / 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

REST_FRAMEWORK = {
     'DEFAULT_AUTHENTICATION_CLASSES': [
         'awcenter.authentication.CookieTokenAuthentication',
     ],
     'DEFAULT_PERMISSION_CLASSES': [
         'rest_framework.permissions.IsAuthenticated',
     ],
     'EXCEPTION_HANDLER': 'awcenter.api_errors.api_exception_handler',
     'DEFAULT_PAGINATION_CLASS': 'awcenter.pagination.StandardResultsSetPagination',
     'PAGE_SIZE': 50,
}

CACHE_URL = env.str("CACHE_URL", default="")
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": CACHE_URL,
    }
    if CACHE_URL
    else {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "awcenter-local-cache",
        "TIMEOUT": 60,
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
        },
    }
}

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = env.str("SESSION_COOKIE_SAMESITE", default="Lax")
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = env.str("CSRF_COOKIE_SAMESITE", default="Lax")
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = env.bool("USE_X_FORWARDED_HOST", default=not DEBUG)
X_FRAME_OPTIONS = "DENY"

LOG_LEVEL = env.str("LOG_LEVEL", default="INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "awcenter.requests": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
