"""
Django settings for awcenter project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from corsheaders.defaults import default_headers, default_methods
from django.core.exceptions import ImproperlyConfigured
import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
ENV_FILE = Path(os.environ.get("AWCENTER_ENV_FILE", BASE_DIR / ".env"))
env.read_env(ENV_FILE)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEV_SECRET_KEY = "aw-center-local-development-secret-key-change-before-production-2026"
SECRET_KEY = env.str("SECRET_KEY", default="")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = DEV_SECRET_KEY
    else:
        raise ImproperlyConfigured("SECRET_KEY must be defined when DEBUG is False.")

IPV4_ADDRESS = env.str("IPV4_ADDRESS")
PORT = env.int("PORT")

DOCPROOF_URL = env.str("DOCPROOF_URL")
DOORS_EXECUTABLE = env.str("DOORS_EXECUTABLE")
DOORS_DATABASE = env.str("DOORS_DATABASE", default="")
DOORS_OLE_PROG_ID = env.str("DOORS_OLE_PROG_ID", default="DOORS.Application")
DOORS_PREFER_ACTIVE_INSTANCE = env.bool("DOORS_PREFER_ACTIVE_INSTANCE", default=True)
DOORS_AUTO_START_CLIENT = env.bool("DOORS_AUTO_START_CLIENT", default=False)
DOORS_STARTUP_TIMEOUT_SECONDS = env.float("DOORS_STARTUP_TIMEOUT_SECONDS", default=30.0)
DOORS_RUN_TIMEOUT_SECONDS = env.float("DOORS_RUN_TIMEOUT_SECONDS", default=120.0)
DOORS_MAX_RESULT_BYTES = env.int("DOORS_MAX_RESULT_BYTES", default=10 * 1024 * 1024)

TEAMCENTER_BASE_URL = env.str("TEAMCENTER_BASE_URL", default="")
TEAMCENTER_SERVICE_ROOT = env.str("TEAMCENTER_SERVICE_ROOT", default="RestServices")
TEAMCENTER_AUTH_MODE = env.str("TEAMCENTER_AUTH_MODE", default="password")
TEAMCENTER_USERNAME = env.str("TEAMCENTER_USERNAME", default="")
TEAMCENTER_PASSWORD = env.str("TEAMCENTER_PASSWORD", default="")
TEAMCENTER_GROUP = env.str("TEAMCENTER_GROUP", default="")
TEAMCENTER_ROLE = env.str("TEAMCENTER_ROLE", default="")
TEAMCENTER_VERIFY_SSL = env.str("TEAMCENTER_VERIFY_SSL", default="true")
TEAMCENTER_JSESSIONID = env.str("TEAMCENTER_JSESSIONID", default="")
TEAMCENTER_XSRF_TOKEN = env.str("TEAMCENTER_XSRF_TOKEN", default="")
TEAMCENTER_CONNECT_TIMEOUT_SECONDS = env.float("TEAMCENTER_CONNECT_TIMEOUT_SECONDS", default=10.0)
TEAMCENTER_READ_TIMEOUT_SECONDS = env.float("TEAMCENTER_READ_TIMEOUT_SECONDS", default=60.0)
TEAMCENTER_MAX_READ_RETRIES = env.int("TEAMCENTER_MAX_READ_RETRIES", default=2)
TEAMCENTER_MAX_RESPONSE_BYTES = env.int("TEAMCENTER_MAX_RESPONSE_BYTES", default=10 * 1024 * 1024)

JIRA_URL = env.str("JIRA_URL")
JIRA_DEFAULT_PROJECT_KEY = env.str("JIRA_DEFAULT_PROJECT_KEY", default="CHN")
JIRA_DRAFT_PUBLISH_STALE_SECONDS = env.int("JIRA_DRAFT_PUBLISH_STALE_SECONDS", default=300)

AW_USERNAME = env.str("AW_USERNAME", "")
AW_PASSWORD = env.str("AW_PASSWORD", "")
FFMPEG_EXECUTABLE = env.str("FFMPEG_EXECUTABLE", default="ffmpeg")


def origin_url(scheme, host, port):
    """Build a browser origin URL from scheme, host, and port."""
    return f"{scheme}://{host}:{port}"


def local_development_origins(frontend_port=5173, backend_port=8000):
    """Return explicit local origins used by Vite and Django development."""
    hosts = ("localhost", "127.0.0.1")
    ports = (frontend_port, backend_port)
    return [origin_url("http", host, port) for host in hosts for port in ports]


def unique_items(items):
    """Return items without duplicates while preserving declaration order."""
    return list(dict.fromkeys(item for item in items if item))


def get_default_auth_cookie_samesite(debug):
    """Return the safe default SameSite policy for the runtime mode."""
    return "Lax" if debug else "None"


def get_default_auth_cookie_secure(debug):
    """Return whether auth cookies should default to Secure for the runtime mode."""
    return not debug


CERTIFICATES_DIR = BASE_DIR / "certificates"
CUSTOM_TEMPLATE_DIR = BASE_DIR / "custom_templates"
WORD_TRANSLATION_TR_EN_MODEL = Path(
    env.path("WORD_TRANSLATION_TR_EN_MODEL", default=BASE_DIR / "models" / "opus-mt-tr-en")
)
WORD_TRANSLATION_EN_TR_MODEL = Path(
    env.path("WORD_TRANSLATION_EN_TR_MODEL", default=BASE_DIR / "models" / "opus-mt-en-tr")
)
WORD_ANALYZER_BI_MODEL = Path(
    env.path("WORD_ANALYZER_BI_MODEL", default=BASE_DIR / "models" / "paraphrase-multilingual")
)
WORD_ANALYZER_CROSS_MODEL = Path(
    env.path("WORD_ANALYZER_CROSS_MODEL", default=BASE_DIR / "models" / "ms-marco-cross-encoder")
)
WORD_ANALYZER_MAX_UNITS = env.int("WORD_ANALYZER_MAX_UNITS", default=10000)
COVER_PAGE_TEMPLATE_PATH = Path(
    env.path("COVER_PAGE_TEMPLATE_PATH", default=CUSTOM_TEMPLATE_DIR / "cover_page_template.docx")
)
COVER_PAGE_MAX_ROWS = env.int("COVER_PAGE_MAX_ROWS", default=1000)
COVER_PAGE_B30_PROJECT_LABEL = env.str(
    "COVER_PAGE_B30_PROJECT_LABEL", default="F-16 Block-30 ÖZGÜR-2 Work Package"
)
COVER_PAGE_DEFAULT_PROJECT_LABEL = env.str(
    "COVER_PAGE_DEFAULT_PROJECT_LABEL", default="AW Center Project"
)
REPOSITORY_DIR = BASE_DIR.parent
FRONTEND_DIST_DIR = Path(env.path("FRONTEND_DIST_DIR", default=REPOSITORY_DIR / "frontend" / "dist"))
FRONTEND_ASSETS_DIR = FRONTEND_DIST_DIR / "assets"
PRIVATE_MEDIA_ROOT = Path(env.path("PRIVATE_MEDIA_ROOT", default=BASE_DIR / "private_media"))

FRONTEND_RESET_URL = env.str(
    "FRONTEND_RESET_URL",
    default=f"http{'s' if not DEBUG else ''}://{IPV4_ADDRESS if not DEBUG else 'localhost'}:{PORT if not DEBUG else 5173}/app/login"
)
FRONTEND_INVITATION_URL = env.str(
    "FRONTEND_INVITATION_URL",
    default=f"http{'s' if not DEBUG else ''}://{IPV4_ADDRESS if not DEBUG else 'localhost'}:{PORT if not DEBUG else 5173}/app/invite",
)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[
    IPV4_ADDRESS, "127.0.0.1", "localhost"
])
if DEBUG and env.bool("ALLOW_ALL_DEBUG_HOSTS", default=True):
    ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'awcenter.admin.AwCenterAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'simple_history',
    'users',
    'common',
    'projects.ozgur',
    'projects.piku',
    'projects.aesa',
    'projects.hys',
    'projects.blok30',
    'projects.blok4050',
    'projects.havasoj',
    'projects.gokbey',
    'dcc',
    'doors',
    'teamcenter',
    'ddf',
    'orgs',
    'pptxgallery',
    'outlook',
    'releases',
    'media_tools',
    'jobs',
    'corsheaders',
]

MIDDLEWARE = [
    'awcenter.request_context.RequestCorrelationMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'awcenter.api_errors.ApiErrorContractMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

if not DEBUG:
    MIDDLEWARE += ['awcenter.middleware.RequestUserLogMiddleware']

DEV_FRONTEND_PORT = env.int("DEV_FRONTEND_PORT", default=5173)
DEV_BACKEND_PORT = env.int("DEV_BACKEND_PORT", default=PORT)
DEV_SERVER_ORIGINS = env.list(
    "DEV_SERVER_ORIGINS",
    default=local_development_origins(DEV_FRONTEND_PORT, DEV_BACKEND_PORT),
)

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = unique_items(DEV_SERVER_ORIGINS)
    CORS_ALLOWED_ORIGIN_REGEXES = env.list(
        "CORS_ALLOWED_ORIGIN_REGEXES",
        default=[r"^https?://localhost:\d+$", r"^https?://127\.0\.0\.1:\d+$"],
    )
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
    CORS_ALLOWED_ORIGIN_REGEXES = env.list("CORS_ALLOWED_ORIGIN_REGEXES", default=[])
    if not CORS_ALLOWED_ORIGINS and not CORS_ALLOWED_ORIGIN_REGEXES:
        raise ImproperlyConfigured("CORS_ALLOWED_ORIGINS must be set when DEBUG is False.")

CORS_ALLOW_HEADERS = [*default_headers, "idempotency-key", "x-request-id"]
CORS_ALLOW_METHODS = list(default_methods)
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ["X-Request-ID"]
CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=unique_items(DEV_SERVER_ORIGINS) if DEBUG else [],
)

# Browser authentication strategy:
# - The SPA uses a DRF token stored in an HttpOnly auth cookie.
# - Header tokens remain supported for non-browser clients and DEBUG fallback.
# - Unsafe cookie-authenticated requests are protected by Django CSRF checks.
#
# Cross-site deployments must use HTTPS, AUTH_COOKIE_SAMESITE=None,
# AUTH_COOKIE_SECURE=True, CORS_ALLOWED_ORIGINS, and CSRF_TRUSTED_ORIGINS.
# Same-site deployments should prefer AUTH_COOKIE_SAMESITE=Lax.
AUTH_COOKIE_NAME = env.str("AUTH_COOKIE_NAME", default="auth_token")
AUTH_COOKIE_MAX_AGE = env.int("AUTH_COOKIE_MAX_AGE", default=60 * 60 * 24 * 14)
AUTH_COOKIE_DEFAULT_SAMESITE = get_default_auth_cookie_samesite(DEBUG)
AUTH_COOKIE_SAMESITE = env.str("AUTH_COOKIE_SAMESITE", default=AUTH_COOKIE_DEFAULT_SAMESITE)
AUTH_COOKIE_SECURE = env.bool("AUTH_COOKIE_SECURE", default=get_default_auth_cookie_secure(DEBUG))
AUTH_TOKEN_RESPONSE_ENABLED = env.bool("AUTH_TOKEN_RESPONSE_ENABLED", default=DEBUG)

ROOT_URLCONF = 'awcenter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            FRONTEND_DIST_DIR,
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'awcenter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
    "db_old": env.db("DB_OLD_URL", default=f"sqlite:///{BASE_DIR / 'db_old.sqlite3'}"),
}
DATABASES["default"]["CONN_MAX_AGE"] = env.int("DATABASE_CONN_MAX_AGE", default=60)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True
USE_TZ = True

DATE_INPUT_FORMATS = ['%d.%m.%Y', '%d/%m/%Y', '%Y-%m-%d']
DATETIME_INPUT_FORMATS = ['%d.%m.%Y %H:%M']
DATE_FORMAT = 'd.m.Y'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/core/'
STATIC_ROOT = Path(env.path('STATIC_ROOT', default=BASE_DIR / 'static'))
STATICFILES_DIRS = [BASE_DIR / 'core']
if FRONTEND_ASSETS_DIR.exists():
    STATICFILES_DIRS.append(('assets', FRONTEND_ASSETS_DIR))
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = Path(env.path('MEDIA_ROOT', default=BASE_DIR / 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
AWCENTER_MAX_DOCUMENT_UPLOAD_BYTES = env.int(
    "AWCENTER_MAX_DOCUMENT_UPLOAD_BYTES", default=50 * 1024 * 1024
)
AWCENTER_MAX_IMAGE_UPLOAD_BYTES = env.int(
    "AWCENTER_MAX_IMAGE_UPLOAD_BYTES", default=10 * 1024 * 1024
)
AWCENTER_MAX_MEDIA_UPLOAD_BYTES = env.int(
    "AWCENTER_MAX_MEDIA_UPLOAD_BYTES", default=500 * 1024 * 1024
)
AWCENTER_ABSOLUTE_MAX_UPLOAD_BYTES = env.int(
    "AWCENTER_ABSOLUTE_MAX_UPLOAD_BYTES", default=600 * 1024 * 1024
)
AWCENTER_MAX_ATTACHMENT_UPLOAD_BYTES = env.int(
    "AWCENTER_MAX_ATTACHMENT_UPLOAD_BYTES", default=100 * 1024 * 1024
)
OUTLOOK_MAX_ATTACHMENTS = env.int("OUTLOOK_MAX_ATTACHMENTS", default=100)
OUTLOOK_PARSE_RATE = env.str("OUTLOOK_PARSE_RATE", default="60/hour")
AWCENTER_MAX_ARCHIVE_EXPANDED_BYTES = env.int(
    "AWCENTER_MAX_ARCHIVE_EXPANDED_BYTES", default=250 * 1024 * 1024
)
AWCENTER_MAX_ARCHIVE_ENTRIES = env.int("AWCENTER_MAX_ARCHIVE_ENTRIES", default=5000)
AWCENTER_MAX_COMPDOC_IMPORT_ROWS = env.int("AWCENTER_MAX_COMPDOC_IMPORT_ROWS", default=10000)
COMPDOC_IMPORT_PREVIEW_TTL_SECONDS = env.int(
    "COMPDOC_IMPORT_PREVIEW_TTL_SECONDS", default=15 * 60
)
SOFFICE_BIN = env.str("SOFFICE_BIN", default="soffice")
PDFTOPPM_BIN = env.str("PDFTOPPM_BIN", default="pdftoppm")
PPTX_CONVERSION_TIMEOUT_SECONDS = env.int("PPTX_CONVERSION_TIMEOUT_SECONDS", default=180)
INTEGRATION_PROBE_CONNECT_TIMEOUT_SECONDS = env.float(
    "INTEGRATION_PROBE_CONNECT_TIMEOUT_SECONDS", default=2.0
)
INTEGRATION_PROBE_READ_TIMEOUT_SECONDS = env.float(
    "INTEGRATION_PROBE_READ_TIMEOUT_SECONDS", default=3.0
)
INTEGRATION_PROBE_CACHE_SECONDS = env.int("INTEGRATION_PROBE_CACHE_SECONDS", default=30)
INTEGRATION_PROBE_REFRESH_COOLDOWN_SECONDS = env.int(
    "INTEGRATION_PROBE_REFRESH_COOLDOWN_SECONDS", default=5
)
INTEGRATION_PROBE_MAX_WORKERS = env.int("INTEGRATION_PROBE_MAX_WORKERS", default=6)
INTEGRATION_PROBE_FAILURE_THRESHOLD = env.int(
    "INTEGRATION_PROBE_FAILURE_THRESHOLD", default=3
)
INTEGRATION_PROBE_FAILURE_WINDOW_SECONDS = env.int(
    "INTEGRATION_PROBE_FAILURE_WINDOW_SECONDS", default=300
)
INTEGRATION_PROBE_CIRCUIT_COOLDOWN_SECONDS = env.int(
    "INTEGRATION_PROBE_CIRCUIT_COOLDOWN_SECONDS", default=120
)
JOB_LEASE_SECONDS = env.int("JOB_LEASE_SECONDS", default=60)
JOB_HEARTBEAT_SECONDS = env.int("JOB_HEARTBEAT_SECONDS", default=2)
JOB_WORKER_STALE_SECONDS = env.int("JOB_WORKER_STALE_SECONDS", default=10)
JOB_EXECUTION_TIMEOUT_SECONDS = env.int("JOB_EXECUTION_TIMEOUT_SECONDS", default=900)
JOB_MAX_OUTPUT_BYTES = env.int("JOB_MAX_OUTPUT_BYTES", default=1024 * 1024 * 1024)
JOB_ARTIFACT_RETENTION_DAYS = env.int("JOB_ARTIFACT_RETENTION_DAYS", default=30)
DCC_PREVIEW_TTL_SECONDS = env.int("DCC_PREVIEW_TTL_SECONDS", default=900)
FILE_UPLOAD_HANDLERS = [
    "awcenter.upload_handlers.AbsoluteUploadLimitHandler",
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]

REST_FRAMEWORK = {
     'DEFAULT_AUTHENTICATION_CLASSES': [
         'awcenter.authentication.CookieTokenAuthentication',
     ],
     'DEFAULT_PERMISSION_CLASSES': [
         'rest_framework.permissions.IsAuthenticated',
     ],
     'EXCEPTION_HANDLER': 'awcenter.api_errors.api_exception_handler',
     'DEFAULT_PAGINATION_CLASS': 'awcenter.pagination.StandardResultsSetPagination',
     'PAGE_SIZE': 50,
     'NUM_PROXIES': env.int('TRUSTED_PROXY_COUNT', default=0),
}

CACHE_URL = env.str("CACHE_URL", default="")
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": CACHE_URL,
    }
    if CACHE_URL
    else {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "awcenter-local-cache",
        "TIMEOUT": 60,
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
        },
    }
}

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = env.str("SESSION_COOKIE_SAMESITE", default="Lax")
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = env.str("CSRF_COOKIE_SAMESITE", default="Lax")
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = env.bool("USE_X_FORWARDED_HOST", default=not DEBUG)
X_FRAME_OPTIONS = "DENY"

LOG_LEVEL = env.str("LOG_LEVEL", default="INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": (
                "%(asctime)s %(levelname)s %(name)s "
                "[request_id=%(request_id)s] %(message)s"
            ),
        },
    },
    "filters": {
        "request_id": {
            "()": "awcenter.request_context.RequestIdLogFilter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
            "filters": ["request_id"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "awcenter.requests": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
