"""
Django settings for awcenter project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from corsheaders.defaults import default_headers, default_methods
from django.core.exceptions import ImproperlyConfigured
import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()


def resolve_environment_file_path(selected_file, base_dir=BASE_DIR):
    """Resolve a backend env file path in a cwd-independent way."""
    environment_file = Path(selected_file).expanduser()
    if not environment_file.is_absolute():
        environment_file = base_dir / environment_file
    return environment_file


def load_environment_files(environment, base_dir=BASE_DIR):
    """Load a selected profile without allowing dotenv values to replace OS values."""

    original_environment = dict(os.environ)
    default_file = base_dir / ".env"
    selected_by_os = original_environment.get("AWCENTER_ENV_FILE")
    if selected_by_os:
        selected_file = resolve_environment_file_path(selected_by_os, base_dir)
        environment.read_env(selected_file)
        return selected_file

    environment.read_env(default_file)
    selected_file = resolve_environment_file_path(
        os.environ.get("AWCENTER_ENV_FILE", ".env"), base_dir
    )
    if selected_file != default_file:
        environment.read_env(selected_file, overwrite=True)
        os.environ.update(original_environment)
    return selected_file


ENV_FILE = load_environment_files(env)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEV_SECRET_KEY = "aw-center-local-development-secret-key-change-before-production-2026"
SECRET_KEY = env.str("SECRET_KEY", default="")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = DEV_SECRET_KEY
    else:
        raise ImproperlyConfigured("SECRET_KEY must be defined when DEBUG is False.")

IPV4_ADDRESS = env.str("IPV4_ADDRESS", default="127.0.0.1")
PORT = env.int("PORT", default=8000)

DOCPROOF_ENABLED = env.bool("DOCPROOF_ENABLED", default=False)
DOCPROOF_URL = env.str("DOCPROOF_URL", default="")
DOCPROOF_VERIFY_SSL = env.bool("DOCPROOF_VERIFY_SSL", default=True)
DOCPROOF_USERNAME = env.str("DOCPROOF_USERNAME", default="")
DOCPROOF_PASSWORD = env.str("DOCPROOF_PASSWORD", default="")
DOCPROOF_MAX_RESPONSE_BYTES = env.int(
    "DOCPROOF_MAX_RESPONSE_BYTES",
    default=10 * 1024 * 1024,
)
DOCPROOF_CERTIFICATE_FILE = Path(
    env.path(
        "DOCPROOF_CERTIFICATE_FILE",
        default=BASE_DIR / "certificates" / "dmntai_intra.crt",
    )
)
DOORS_ENABLED = env.bool("DOORS_ENABLED", default=False)
DOORS_EXECUTABLE = env.str("DOORS_EXECUTABLE", default="")
DOORS_DATABASE = env.str("DOORS_DATABASE", default="")
DOORS_OLE_PROG_ID = env.str("DOORS_OLE_PROG_ID", default="DOORS.Application")
DOORS_PREFER_ACTIVE_INSTANCE = env.bool("DOORS_PREFER_ACTIVE_INSTANCE", default=True)
DOORS_AUTO_START_CLIENT = env.bool("DOORS_AUTO_START_CLIENT", default=False)
DOORS_STARTUP_TIMEOUT_SECONDS = env.float("DOORS_STARTUP_TIMEOUT_SECONDS", default=30.0)
DOORS_RUN_TIMEOUT_SECONDS = env.float("DOORS_RUN_TIMEOUT_SECONDS", default=120.0)
DOORS_MAX_RESULT_BYTES = env.int("DOORS_MAX_RESULT_BYTES", default=10 * 1024 * 1024)
DOORS_RESULT_MODE = env.str("DOORS_RESULT_MODE", default="file")
DOORS_RUNNER_TOKEN = env.str("DOORS_RUNNER_TOKEN", default="")
DOORS_RUNNER_URL = env.str("DOORS_RUNNER_URL", default="http://127.0.0.1:8765")
DOORS_RUNNER_CREDENTIAL_TARGET = env.str(
    "DOORS_RUNNER_CREDENTIAL_TARGET", default="AWCenter/DOORSRunner"
)
DOORS_RUNNER_CONNECT_TIMEOUT_SECONDS = env.float(
    "DOORS_RUNNER_CONNECT_TIMEOUT_SECONDS", default=5.0
)
DOORS_RUNNER_READ_TIMEOUT_SECONDS = env.float(
    "DOORS_RUNNER_READ_TIMEOUT_SECONDS", default=30.0
)
DOORS_RUNNER_MAX_INPUT_BYTES = env.int(
    "DOORS_RUNNER_MAX_INPUT_BYTES", default=1024 * 1024
)

TEAMCENTER_ENABLED = env.bool("TEAMCENTER_ENABLED", default=False)
TEAMCENTER_BASE_URL = env.str("TEAMCENTER_BASE_URL", default="")
TEAMCENTER_SERVICE_ROOT = env.str("TEAMCENTER_SERVICE_ROOT", default="RestServices")
TEAMCENTER_AUTH_MODE = env.str("TEAMCENTER_AUTH_MODE", default="password")
TEAMCENTER_USERNAME = env.str("TEAMCENTER_USERNAME", default="")
TEAMCENTER_PASSWORD = env.str("TEAMCENTER_PASSWORD", default="")
TEAMCENTER_GROUP = env.str("TEAMCENTER_GROUP", default="")
TEAMCENTER_ROLE = env.str("TEAMCENTER_ROLE", default="")
TEAMCENTER_VERIFY_SSL = env.bool("TEAMCENTER_VERIFY_SSL", default=True)
TEAMCENTER_JSESSIONID = env.str("TEAMCENTER_JSESSIONID", default="")
TEAMCENTER_XSRF_TOKEN = env.str("TEAMCENTER_XSRF_TOKEN", default="")
TEAMCENTER_CONNECT_TIMEOUT_SECONDS = env.float("TEAMCENTER_CONNECT_TIMEOUT_SECONDS", default=10.0)
TEAMCENTER_READ_TIMEOUT_SECONDS = env.float("TEAMCENTER_READ_TIMEOUT_SECONDS", default=60.0)
TEAMCENTER_MAX_READ_RETRIES = env.int("TEAMCENTER_MAX_READ_RETRIES", default=2)
TEAMCENTER_MAX_RESPONSE_BYTES = env.int("TEAMCENTER_MAX_RESPONSE_BYTES", default=10 * 1024 * 1024)

JIRA_ENABLED = env.bool("JIRA_ENABLED", default=False)
JIRA_URL = env.str("JIRA_URL", default="")
JIRA_DEFAULT_PROJECT_KEY = env.str("JIRA_DEFAULT_PROJECT_KEY", default="CHN")
JIRA_DRAFT_PUBLISH_STALE_SECONDS = env.int("JIRA_DRAFT_PUBLISH_STALE_SECONDS", default=300)
JIRA_SESSION_TTL_SECONDS = env.int("JIRA_SESSION_TTL_SECONDS", default=3600)
JIRA_SESSION_ENCRYPTION_KEY = env.str("JIRA_SESSION_ENCRYPTION_KEY", default="")
ASSESSMENT_API_URL = env.str("ASSESSMENT_API_URL", default="")
ASSESSMENT_API_ALLOWED_HOSTS = env.list("ASSESSMENT_API_ALLOWED_HOSTS", default=[])
ASSESSMENT_API_CONNECT_TIMEOUT_SECONDS = env.float(
    "ASSESSMENT_API_CONNECT_TIMEOUT_SECONDS", default=5.0
)
ASSESSMENT_API_READ_TIMEOUT_SECONDS = env.float(
    "ASSESSMENT_API_READ_TIMEOUT_SECONDS", default=60.0
)
ASSESSMENT_API_MAX_RESPONSE_BYTES = env.int(
    "ASSESSMENT_API_MAX_RESPONSE_BYTES", default=1024 * 1024
)

FFMPEG_EXECUTABLE = env.str("FFMPEG_EXECUTABLE", default="ffmpeg")


def origin_url(scheme, host, port):
    """Build a browser origin URL from scheme, host, and port."""
    return f"{scheme}://{host}:{port}"


def local_development_origins(frontend_port=5173, backend_port=8000):
    """Return explicit local origins used by Vite and Django development."""
    hosts = ("localhost", "127.0.0.1")
    ports = (frontend_port, backend_port)
    return [origin_url("http", host, port) for host in hosts for port in ports]


def unique_items(items):
    """Return items without duplicates while preserving declaration order."""
    return list(dict.fromkeys(item for item in items if item))


CERTIFICATES_DIR = BASE_DIR / "certificates"
MODEL_RUNTIME_DIR = Path(
    env.path(
        "MODEL_RUNTIME_DIR",
        default=BASE_DIR.parent / ".runtime" / "ai-models",
    )
)
CUSTOM_TEMPLATE_DIR = Path(
    env.path(
        "CUSTOM_TEMPLATE_DIR",
        default=BASE_DIR.parent / ".runtime" / "document-templates",
    )
)
WORD_TRANSLATION_TR_EN_MODEL = Path(
    env.path("WORD_TRANSLATION_TR_EN_MODEL", default=MODEL_RUNTIME_DIR / "opus-mt-tr-en")
)
WORD_TRANSLATION_EN_TR_MODEL = Path(
    env.path("WORD_TRANSLATION_EN_TR_MODEL", default=MODEL_RUNTIME_DIR / "opus-mt-en-tr")
)
WORD_ANALYZER_BI_MODEL = Path(
    env.path("WORD_ANALYZER_BI_MODEL", default=MODEL_RUNTIME_DIR / "paraphrase-multilingual")
)
WORD_ANALYZER_CROSS_MODEL = Path(
    env.path("WORD_ANALYZER_CROSS_MODEL", default=MODEL_RUNTIME_DIR / "ms-marco-cross-encoder")
)
WORD_ANALYZER_MAX_UNITS = env.int("WORD_ANALYZER_MAX_UNITS", default=10000)
COVER_PAGE_TEMPLATE_PATH = Path(
    env.path("COVER_PAGE_TEMPLATE_PATH", default=CUSTOM_TEMPLATE_DIR / "cover_page_template.docx")
)
COVER_PAGE_MAX_ROWS = env.int("COVER_PAGE_MAX_ROWS", default=1000)
COVER_PAGE_B30_PROJECT_LABEL = env.str(
    "COVER_PAGE_B30_PROJECT_LABEL", default="F-16 Block-30 ÖZGÜR-2 Work Package"
)
COVER_PAGE_DEFAULT_PROJECT_LABEL = env.str(
    "COVER_PAGE_DEFAULT_PROJECT_LABEL", default="AW Center Project"
)
REPOSITORY_DIR = BASE_DIR.parent
FRONTEND_DIST_DIR = Path(env.path("FRONTEND_DIST_DIR", default=REPOSITORY_DIR / "frontend" / "dist"))
FRONTEND_ASSETS_DIR = FRONTEND_DIST_DIR / "assets"
PRIVATE_MEDIA_ROOT = Path(env.path("PRIVATE_MEDIA_ROOT", default=BASE_DIR / "private_media"))

FRONTEND_RESET_URL = env.str(
    "FRONTEND_RESET_URL",
    default=f"http{'s' if not DEBUG else ''}://{IPV4_ADDRESS if not DEBUG else 'localhost'}:{PORT if not DEBUG else 5173}/app/login"
)
FRONTEND_INVITATION_URL = env.str(
    "FRONTEND_INVITATION_URL",
    default=f"http{'s' if not DEBUG else ''}://{IPV4_ADDRESS if not DEBUG else 'localhost'}:{PORT if not DEBUG else 5173}/app/invite",
)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[
    IPV4_ADDRESS, "127.0.0.1", "localhost"
])
if DEBUG and env.bool("ALLOW_ALL_DEBUG_HOSTS", default=True):
    ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'awcenter.admin.AwCenterAdminConfig',
    'awcenter',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'simple_history',
    'users',
    'integrations',
    'automations',
    'compliance',
    'attention',
    'dcc',
    'ddf',
    'orgs',
    'pptxgallery',
    'outlook',
    'releases',
    'media_tools',
    'jobs',
    'corsheaders',
]

MIDDLEWARE = [
    'awcenter.request_context.RequestCorrelationMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'awcenter.api_errors.ApiErrorContractMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

if not DEBUG:
    MIDDLEWARE += ['awcenter.middleware.RequestUserLogMiddleware']

DEV_FRONTEND_PORT = env.int("DEV_FRONTEND_PORT", default=5173)
DEV_BACKEND_PORT = env.int("DEV_BACKEND_PORT", default=PORT)
DEV_SERVER_ORIGINS = env.list(
    "DEV_SERVER_ORIGINS",
    default=local_development_origins(DEV_FRONTEND_PORT, DEV_BACKEND_PORT),
)

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = unique_items(DEV_SERVER_ORIGINS)
    CORS_ALLOWED_ORIGIN_REGEXES = env.list(
        "CORS_ALLOWED_ORIGIN_REGEXES",
        default=[r"^https?://localhost:\d+$", r"^https?://127\.0\.0\.1:\d+$"],
    )
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
    CORS_ALLOWED_ORIGIN_REGEXES = env.list("CORS_ALLOWED_ORIGIN_REGEXES", default=[])

CORS_ALLOW_HEADERS = [*default_headers, "idempotency-key", "x-request-id"]
CORS_ALLOW_METHODS = list(default_methods)
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ["X-Request-ID"]
CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=unique_items(DEV_SERVER_ORIGINS) if DEBUG else [],
)

ROOT_URLCONF = 'awcenter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            FRONTEND_DIST_DIR,
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'awcenter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def configure_sqlite_concurrency(database, busy_timeout_seconds):
    """Serialize SQLite writers before reads can create lock-upgrade races."""

    if database.get("ENGINE") != "django.db.backends.sqlite3":
        return
    if busy_timeout_seconds <= 0:
        raise ImproperlyConfigured(
            "SQLITE_BUSY_TIMEOUT_SECONDS must be greater than zero."
        )
    options = database.setdefault("OPTIONS", {})
    options["timeout"] = busy_timeout_seconds
    options["transaction_mode"] = "IMMEDIATE"


DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
}
DATABASES["default"]["CONN_MAX_AGE"] = env.int("DATABASE_CONN_MAX_AGE", default=60)
configure_sqlite_concurrency(
    DATABASES["default"],
    env.float("SQLITE_BUSY_TIMEOUT_SECONDS", default=30.0),
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True
USE_TZ = True

DATE_INPUT_FORMATS = ['%d.%m.%Y', '%d/%m/%Y', '%Y-%m-%d']
DATETIME_INPUT_FORMATS = ['%d.%m.%Y %H:%M']
DATE_FORMAT = 'd.m.Y'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/core/'
STATIC_ROOT = Path(env.path('STATIC_ROOT', default=BASE_DIR / 'static'))
STATICFILES_DIRS = []
if FRONTEND_ASSETS_DIR.exists():
    STATICFILES_DIRS.append(('assets', FRONTEND_ASSETS_DIR))
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = Path(env.path('MEDIA_ROOT', default=BASE_DIR / 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
AWCENTER_MAX_DOCUMENT_UPLOAD_BYTES = env.int(
    "AWCENTER_MAX_DOCUMENT_UPLOAD_BYTES", default=50 * 1024 * 1024
)
AWCENTER_MAX_IMAGE_UPLOAD_BYTES = env.int(
    "AWCENTER_MAX_IMAGE_UPLOAD_BYTES", default=10 * 1024 * 1024
)
AWCENTER_MAX_MEDIA_UPLOAD_BYTES = env.int(
    "AWCENTER_MAX_MEDIA_UPLOAD_BYTES", default=500 * 1024 * 1024
)
AWCENTER_ABSOLUTE_MAX_UPLOAD_BYTES = env.int(
    "AWCENTER_ABSOLUTE_MAX_UPLOAD_BYTES", default=600 * 1024 * 1024
)
AWCENTER_MAX_ATTACHMENT_UPLOAD_BYTES = env.int(
    "AWCENTER_MAX_ATTACHMENT_UPLOAD_BYTES", default=100 * 1024 * 1024
)
OUTLOOK_MAX_ATTACHMENTS = env.int("OUTLOOK_MAX_ATTACHMENTS", default=100)
OUTLOOK_PARSE_RATE = env.str("OUTLOOK_PARSE_RATE", default="60/hour")
AWCENTER_MAX_ARCHIVE_EXPANDED_BYTES = env.int(
    "AWCENTER_MAX_ARCHIVE_EXPANDED_BYTES", default=250 * 1024 * 1024
)
AWCENTER_MAX_ARCHIVE_ENTRIES = env.int("AWCENTER_MAX_ARCHIVE_ENTRIES", default=5000)
AWCENTER_MAX_COMPDOC_IMPORT_ROWS = env.int("AWCENTER_MAX_COMPDOC_IMPORT_ROWS", default=10000)
AWCENTER_MAX_COMPDOC_EXPORT_ROWS = env.int("AWCENTER_MAX_COMPDOC_EXPORT_ROWS", default=10000)
AWCENTER_MAX_PANEL_IMPORT_ROWS = env.int("AWCENTER_MAX_PANEL_IMPORT_ROWS", default=10000)
PANEL_IMPORT_PREVIEW_TTL_SECONDS = env.int(
    "PANEL_IMPORT_PREVIEW_TTL_SECONDS", default=15 * 60
)
COMPDOC_IMPORT_PREVIEW_TTL_SECONDS = env.int(
    "COMPDOC_IMPORT_PREVIEW_TTL_SECONDS", default=15 * 60
)
COMPDOC_NOTIFICATION_POLL_SECONDS = env.int(
    "COMPDOC_NOTIFICATION_POLL_SECONDS", default=5 * 60
)
COMPDOC_NOTIFICATION_BATCH_SIZE = env.int(
    "COMPDOC_NOTIFICATION_BATCH_SIZE", default=25
)
COMPDOC_NOTIFICATION_LOCK_SECONDS = env.int(
    "COMPDOC_NOTIFICATION_LOCK_SECONDS", default=15 * 60
)
COMPDOC_NOTIFICATION_RETRY_SECONDS = env.int(
    "COMPDOC_NOTIFICATION_RETRY_SECONDS", default=60 * 60
)
COMPDOC_DOCPROOF_REFRESH_SECONDS = env.int(
    "COMPDOC_DOCPROOF_REFRESH_SECONDS", default=30 * 60
)
AWCENTER_MAIL_TRANSPORT = env.str("AWCENTER_MAIL_TRANSPORT", default="disabled").lower()
if AWCENTER_MAIL_TRANSPORT not in {"django", "disabled"}:
    raise ImproperlyConfigured(
        "AWCENTER_MAIL_TRANSPORT must be django or disabled."
    )
EMAIL_BACKEND = env.str(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = env.str("EMAIL_HOST", default="localhost")
EMAIL_PORT = env.int("EMAIL_PORT", default=25)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default="awcenter@localhost")
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured("EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be enabled.")
SOFFICE_BIN = env.str("SOFFICE_BIN", default="soffice")
PDFTOPPM_BIN = env.str("PDFTOPPM_BIN", default="pdftoppm")
PPTX_CONVERSION_TIMEOUT_SECONDS = env.int("PPTX_CONVERSION_TIMEOUT_SECONDS", default=180)
INTEGRATION_PROBE_CONNECT_TIMEOUT_SECONDS = env.float(
    "INTEGRATION_PROBE_CONNECT_TIMEOUT_SECONDS", default=2.0
)
INTEGRATION_PROBE_READ_TIMEOUT_SECONDS = env.float(
    "INTEGRATION_PROBE_READ_TIMEOUT_SECONDS", default=3.0
)
INTEGRATION_PROBE_CACHE_SECONDS = env.int("INTEGRATION_PROBE_CACHE_SECONDS", default=30)
INTEGRATION_PROBE_REFRESH_COOLDOWN_SECONDS = env.int(
    "INTEGRATION_PROBE_REFRESH_COOLDOWN_SECONDS", default=5
)
INTEGRATION_PROBE_MAX_WORKERS = env.int("INTEGRATION_PROBE_MAX_WORKERS", default=6)
INTEGRATION_PROBE_FAILURE_THRESHOLD = env.int(
    "INTEGRATION_PROBE_FAILURE_THRESHOLD", default=3
)
INTEGRATION_PROBE_FAILURE_WINDOW_SECONDS = env.int(
    "INTEGRATION_PROBE_FAILURE_WINDOW_SECONDS", default=300
)
INTEGRATION_PROBE_CIRCUIT_COOLDOWN_SECONDS = env.int(
    "INTEGRATION_PROBE_CIRCUIT_COOLDOWN_SECONDS", default=120
)
JOB_LEASE_SECONDS = env.int("JOB_LEASE_SECONDS", default=60)
JOB_HEARTBEAT_SECONDS = env.int("JOB_HEARTBEAT_SECONDS", default=2)
JOB_WORKER_STALE_SECONDS = env.int("JOB_WORKER_STALE_SECONDS", default=10)
JOB_EXECUTION_TIMEOUT_SECONDS = env.int("JOB_EXECUTION_TIMEOUT_SECONDS", default=900)
JOB_MAX_OUTPUT_BYTES = env.int("JOB_MAX_OUTPUT_BYTES", default=1024 * 1024 * 1024)
JOB_ARTIFACT_RETENTION_DAYS = env.int("JOB_ARTIFACT_RETENTION_DAYS", default=30)
DCC_PREVIEW_TTL_SECONDS = env.int("DCC_PREVIEW_TTL_SECONDS", default=900)
FILE_UPLOAD_HANDLERS = [
    "awcenter.upload_handlers.AbsoluteUploadLimitHandler",
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]

TRUSTED_PROXY_COUNT = env.int("TRUSTED_PROXY_COUNT", default=0)

REST_FRAMEWORK = {
     'DEFAULT_AUTHENTICATION_CLASSES': [
         'rest_framework.authentication.SessionAuthentication',
     ],
     'DEFAULT_PERMISSION_CLASSES': [
         'rest_framework.permissions.IsAuthenticated',
     ],
     'EXCEPTION_HANDLER': 'awcenter.api_errors.api_exception_handler',
     'DEFAULT_PAGINATION_CLASS': 'awcenter.pagination.StandardResultsSetPagination',
     'PAGE_SIZE': 50,
     'NUM_PROXIES': TRUSTED_PROXY_COUNT,
}

CACHE_URL = env.str("CACHE_URL", default="")
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": CACHE_URL,
    }
    if CACHE_URL
    else {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "awcenter-local-cache",
        "TIMEOUT": 60,
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
        },
    }
}

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = env.str("SESSION_COOKIE_SAMESITE", default="Lax")
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_AGE = env.int("SESSION_COOKIE_AGE", default=60 * 60 * 12)
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = env.str("CSRF_COOKIE_SAMESITE", default="Lax")
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
TRUST_PROXY_HEADERS = env.bool("TRUST_PROXY_HEADERS", default=False)
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https") if TRUST_PROXY_HEADERS else None
)
USE_X_FORWARDED_HOST = TRUST_PROXY_HEADERS
X_FRAME_OPTIONS = "DENY"

LOG_LEVEL = env.str("LOG_LEVEL", default="INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {"()": "awcenter.logging.JsonEventFormatter"},
    },
    "filters": {
        "request_id": {
            "()": "awcenter.request_context.RequestIdLogFilter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
            "filters": ["request_id"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "awcenter.requests": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
