# Generated by Django 5.2.15 on 2026-07-19 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('worker_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField(auto_now=True)),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
            ],
            options={
                'ordering': ['-heartbeat_at'],
            },
        ),
    ]
