# Generated by Django 5.2.15 on 2026-07-19 00:18

import jobs.models
import jobs.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_workerheartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='input_file',
            field=models.FileField(max_length=500, storage=jobs.storage.PrivateJobStorage(), upload_to=jobs.models.job_input_path),
        ),
        migrations.AlterField(
            model_name='job',
            name='output_file',
            field=models.FileField(blank=True, max_length=500, storage=jobs.storage.PrivateJobStorage(), upload_to=jobs.models.job_output_path),
        ),
    ]
