# Generated by Django 5.2.15 on 2026-07-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_input_file_alter_job_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='retryable',
            field=models.BooleanField(default=True),
        ),
    ]
