# Generated by Django 5.2.15 on 2026-07-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_result_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source_job',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='handoff_jobs',
                to='jobs.job',
            ),
        ),
    ]
