# Generated by Django 5.2.15 on 2026-07-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_workflow_step_workflowrun_job_workflow_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('cancel_requested', 'Cancel requested'), ('cancelled', 'Cancelled'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=24),
        ),
        migrations.AlterField(
            model_name='workflowrunevent',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('cancel_requested', 'Cancel requested'), ('cancelled', 'Cancelled'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=24),
        ),
    ]
