# Generated by Django 6.0 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_alter_job_retry_of_job_jobs_unique_direct_retry"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="confirmation_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting_confirmation", "Awaiting confirmation"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("cancel_requested", "Cancel requested"),
                    ("cancelled", "Cancelled"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="jobevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting_confirmation", "Awaiting confirmation"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("cancel_requested", "Cancel requested"),
                    ("cancelled", "Cancelled"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                max_length=24,
            ),
        ),
    ]
