# Generated by Django 5.2 on 2025-07-31 10:35

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(blank=True, max_length=128, null=True)),
                ('signature_panel', models.CharField(blank=True, max_length=128, null=True)),
                ('ata', models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Ata chapter must consist of four digits.')])),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('cover_page_no', models.CharField(blank=True, max_length=32, null=True)),
                ('cover_page_issue', models.IntegerField(blank=True, null=True)),
                ('tech_doc_no', models.CharField(blank=True, max_length=64, null=True)),
                ('tech_doc_issue', models.IntegerField(blank=True, null=True)),
                ('delivered_tech_doc_issue', models.IntegerField(blank=True, null=True)),
                ('responsible', models.CharField(blank=True, max_length=64, null=True)),
                ('loi', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('not_retained', 'Not Retained'), ('retained', 'Retained')], max_length=12, null=True)),
                ('moc', models.CharField(blank=True, max_length=1, null=True)),
                ('status_flow', models.JSONField(default=list)),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
