# Generated by Django 5.2 on 2025-08-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compdoc',
            name='requirements',
            field=models.JSONField(default=list),
        ),
    ]
