# Generated by Django 5.2 on 2025-08-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_abscompdoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbsCompDoc',
        ),
    ]
