# Generated by Django 5.2 on 2025-08-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesa', '0002_compdoc_delete_aesacompdoc'),
        ('common', '0005_tempcompdoc'),
        ('ozgur', '0002_compdoc_delete_ozgurcompdoc'),
        ('piku', '0003_compdoc_delete_pikucompdoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompDoc',
        ),
    ]
