# Generated by Django 5.2 on 2025-08-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_delete_compdoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempCompDoc',
        ),
    ]
