# Generated by Django 5.2.15 on 2026-07-21 21:03

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_compdocimportaudit_unchanged_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_slug', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=32)),
                ('issue', models.CharField(blank=True, null=True)),
            ],
            options={
                'ordering': ['project_slug', 'number'],
                'constraints': [models.UniqueConstraint(fields=('project_slug', 'number'), name='common_unique_project_cover_page')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCoverPage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('project_slug', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=32)),
                ('issue', models.CharField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cover page',
                'verbose_name_plural': 'historical cover pages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
