# Generated by Django 5.2.15 on 2026-07-28 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_backfill_compdoc_workflow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompDocTrackingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_slug', models.CharField(max_length=64)),
                ('document_id', models.UUIDField()),
                ('responsible_mode', models.CharField(choices=[('automatic', 'Automatic from ATA'), ('custom', 'Custom selection')], default='automatic', max_length=16)),
                ('responsible_person_ids', models.JSONField(blank=True, default=list)),
                ('notification_enabled', models.BooleanField(default=False)),
                ('notification_events', models.JSONField(blank=True, default=list)),
                ('docproof_issue', models.CharField(blank=True, max_length=32)),
                ('docproof_status', models.CharField(default='never_checked', max_length=32)),
                ('docproof_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_compdoc_tracking_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project_slug', 'document_id'],
            },
        ),
        migrations.CreateModel(
            name='CompDocNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=32)),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('recipient_count', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='common.compdoctrackingprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='compdoctrackingprofile',
            index=models.Index(fields=['notification_enabled', 'project_slug'], name='common_compdoc_notify_idx'),
        ),
        migrations.AddConstraint(
            model_name='compdoctrackingprofile',
            constraint=models.UniqueConstraint(fields=('project_slug', 'document_id'), name='common_unique_compdoc_tracking_profile'),
        ),
        migrations.AddIndex(
            model_name='compdocnotificationlog',
            index=models.Index(fields=['profile', 'created_at'], name='common_comp_profile_9ecf0f_idx'),
        ),
    ]
