# Generated by Django 5.2.15 on 2026-07-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_compdoctrackingprofile_compdocnotificationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compdocnotificationlog',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compdocnotificationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='compdoctrackingprofile',
            name='notification_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
