# Generated by Django 5.2.15 on 2026-07-28 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_compdocnotificationlog_attempt_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compdocnotificationlog',
            name='escalation_recipient_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compdocnotificationlog',
            name='policy_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compdocnotificationlog',
            name='primary_recipient_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compdoctrackingprofile',
            name='docproof_issue_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompDocNotificationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_slug', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('event_rules', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('change_note', models.CharField(max_length=255)),
                ('updated_by_username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compdoc_notification_policy_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'permissions': [('manage_compdoc_notification_policy', 'Can manage CompDoc notification policy')],
                'constraints': [models.UniqueConstraint(fields=('project_slug', 'version'), name='common_unique_compdoc_policy_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project_slug',), name='common_unique_active_compdoc_policy')],
            },
        ),
    ]
