# Generated by Django 5.2.15 on 2026-07-28 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_compdocnotificationlog_escalation_recipient_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompDocReviewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_slug', models.CharField(max_length=64)),
                ('document_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('review', 'Review'), ('approval', 'Approval')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('assignee_username', models.CharField(max_length=150)),
                ('requested_by_username', models.CharField(max_length=150)),
                ('decided_by_username', models.CharField(blank=True, max_length=150)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('request_note', models.CharField(max_length=500)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('source_history_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compdoc_review_tasks', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_compdoc_reviews', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_compdoc_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('manage_compdoc_workflow', 'Can manage CompDoc workflow tasks')],
                'indexes': [models.Index(fields=['project_slug', 'document_id', 'status'], name='common_comp_project_f45286_idx'), models.Index(fields=['assignee', 'status', 'due_date'], name='common_comp_assigne_9bb7f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompDocWorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_slug', models.CharField(max_length=64)),
                ('document_id', models.UUIDField()),
                ('sequence', models.PositiveIntegerField()),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('effective_date', models.DateField()),
                ('next_action_due_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('migration', 'Migration')], max_length=16)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-sequence'],
                'indexes': [models.Index(fields=['project_slug', 'document_id', 'created_at'], name='common_comp_project_3a0295_idx')],
                'constraints': [models.UniqueConstraint(fields=('project_slug', 'document_id', 'sequence'), name='common_unique_compdoc_workflow_sequence')],
            },
        ),
    ]
