# Generated by Django 5.2.15 on 2026-07-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_backfill_compdoc_workflow_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverpage',
            name='issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoverpage',
            name='issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
