# Generated by Django 5.2 on 2025-09-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdoc',
            name='cover_page_issue',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='delivered_tech_doc_issue',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='compdoc',
            name='tech_doc_issue',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='cover_page_issue',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='delivered_tech_doc_issue',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalcompdoc',
            name='tech_doc_issue',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]
