# Generated by Django 5.2 on 2025-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys', '0002_alter_compdoc_cover_page_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compdoc',
            name='mom_no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompdoc',
            name='mom_no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
