# Generated by Django 5.2.15 on 2026-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hys", "0013_alter_compdoc_cover_page_issue_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compdoc",
            options={"ordering": ["-created_time", "name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="panel",
            options={"ordering": ["ata", "name"]},
        ),
        migrations.AlterModelOptions(
            name="responsible",
            options={"ordering": ["name", "person_id"]},
        ),
    ]
