# Generated by Django 5.2 on 2025-08-06 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255, )),
                ('doc_name', models.CharField(max_length=255, )),
                ('doc_no', models.CharField(max_length=255, )),
                ('doc_issue', models.CharField(max_length=255, )),
                ('date', models.CharField(max_length=255, )),
                ('commentor', models.CharField(max_length=255, )),
                ('comments', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
