# Generated by Django 5.2 on 2025-08-06 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddf',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
