# Generated by Django 5.2 on 2025-08-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddf', '0002_ddf_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddf',
            name='path',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]
