# Generated by Django 5.2 on 2025-08-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddf', '0003_ddf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddf',
            name='comment_types',
            field=models.JSONField(default=list),
        ),
    ]
