# Generated by Django 5.2.15 on 2026-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddf', '0004_ddf_comment_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddf',
            name='commentor',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='doc_issue',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='doc_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='doc_no',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='path',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='project',
            field=models.CharField(),
        ),
    ]
