# Generated by Django 5.2.15 on 2026-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddf", "0005_alter_ddf_commentor_alter_ddf_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ddf",
            options={"ordering": ["-created_time", "doc_no", "id"]},
        ),
    ]
