# Generated by Django 5.2.15 on 2026-07-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddf', '0006_alter_ddf_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddf',
            name='commentor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='doc_issue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='doc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='doc_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ddf',
            name='project',
            field=models.CharField(max_length=255),
        ),
    ]
