# Generated by Django 5.2 on 2025-12-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name': 'User Preference', 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='compact_view',
            field=models.BooleanField(default=False, help_text='Use compact view mode'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False, help_text='Subscribe to newsletter'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='show_activity',
            field=models.BooleanField(default=True, help_text='Show activity history to others'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='show_online_status',
            field=models.BooleanField(default=True, help_text='Show online status to others'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Receive SMS notifications'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'Eastern Time'), ('America/Los_Angeles', 'Pacific Time'), ('Europe/London', 'London'), ('Europe/Paris', 'Paris'), ('Asia/Tokyo', 'Tokyo')], default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='extra_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Additional custom settings'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='items_per_page',
            field=models.PositiveIntegerField(default=25, help_text='Number of items per page'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='profile_visible',
            field=models.BooleanField(default=True, help_text='Make profile visible to others'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Receive push notifications'),
        ),
    ]
