# Generated by Django 5.2 on 2025-12-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userpreferences_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='has_particles',
            field=models.BooleanField(default=False, help_text='Show particles in the background'),
        ),
    ]
