# Generated by Django 5.2 on 2025-12-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreferences_has_particles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='jira_list',
            field=models.JSONField(blank=True, default=dict, help_text='JIRA subtask list'),
        ),
    ]
