# Generated by Django 5.2 on 2026-01-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreferences_jira_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=5),
        ),
    ]
