# Generated by OpenAI Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userpreferences_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='jira_list',
            field=models.JSONField(blank=True, default=list, help_text='JIRA subtask list'),
        ),
    ]
