# Generated by Django 5.2.15 on 2026-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userpreferences_jira_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpreferences",
            options={
                "ordering": ["user__username", "user_id"],
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
    ]
