"""Central read-only registry for AW Center project applications."""

from types import MappingProxyType

from .types import ProjectDefinition

PROJECT_DEFINITIONS = MappingProxyType(
    {
        "ozgur": ProjectDefinition(
            slug="ozgur",
            display_name="Ozgur",
            app_label="ozgur",
            url_prefix="ozgur",
            enabled=True,
            capabilities=("dcc", "compdocs", "orgs"),
            tags=("active", "certification", "jira"),
            jira_component="OZGUR",
            dcc_label="Ozgur DCC",
            dcc_template_name="ozgur_dcc_template",
            mail_template_name="ozgur_mail_template",
        ),
        "piku": ProjectDefinition(
            slug="piku",
            display_name="Piku",
            app_label="piku",
            url_prefix="piku",
            enabled=True,
            capabilities=("dcc", "compdocs", "orgs"),
            tags=("active", "certification", "jira"),
            jira_component="PIKU",
            dcc_label="Piku DCC",
            dcc_template_name="piku_dcc_template",
            mail_template_name="piku_mail_template",
        ),
        "aesa": ProjectDefinition(
            slug="aesa",
            display_name="AESA",
            app_label="aesa",
            url_prefix="aesa",
            enabled=True,
            capabilities=("dcc", "compdocs", "orgs"),
            tags=("active", "certification", "jira"),
            jira_component="AESA",
            dcc_label="AESA DCC",
            dcc_template_name="aesa_dcc_template",
            mail_template_name="aesa_mail_template",
        ),
        "havasoj": ProjectDefinition(
            slug="havasoj",
            display_name="Havasoj",
            app_label="havasoj",
            url_prefix="havasoj",
            enabled=True,
            capabilities=("dcc", "compdocs", "orgs"),
            tags=("active", "certification", "jira"),
            jira_component="HAVASOJ",
            dcc_label="Havasoj DCC",
            dcc_template_name="havasoj_dcc_template",
            mail_template_name="havasoj_mail_template",
        ),
        "hys": ProjectDefinition(
            slug="hys",
            display_name="HYS",
            app_label="hys",
            url_prefix="hys",
            enabled=True,
            capabilities=("dcc", "compdocs", "orgs"),
            tags=("active", "certification", "jira"),
            jira_component="HYS",
            dcc_label="HYS DCC",
            dcc_template_name="hys_dcc_template",
            mail_template_name="hys_mail_template",
        ),
        "blok30": ProjectDefinition(
            slug="blok30",
            display_name="Blok 30",
            app_label="blok30",
            url_prefix="blok30",
            enabled=True,
            capabilities=("dcc", "compdocs", "orgs"),
            tags=("active", "certification", "jira"),
            jira_component="BLOK30",
            dcc_label="Blok 30 DCC",
            dcc_template_name="blok30_dcc_template",
            mail_template_name="blok30_mail_template",
        ),
        "blok4050": ProjectDefinition(
            slug="blok4050",
            display_name="Blok 40/50",
            app_label="blok4050",
            url_prefix="blok4050",
            enabled=False,
            capabilities=("dcc", "compdocs", "orgs"),
            tags=("inactive", "certification", "jira"),
            jira_component="BLOK4050",
            dcc_label="Blok 40/50 DCC",
            dcc_template_name="blok4050_dcc_template",
            mail_template_name="blok4050_mail_template",
        ),
        "gokbey": ProjectDefinition(
            slug="gokbey",
            display_name="Gokbey",
            app_label="gokbey",
            url_prefix="gokbey",
            enabled=False,
            capabilities=("dcc", "compdocs", "orgs"),
            tags=("inactive", "certification", "jira"),
            jira_component="GOKBEY",
            dcc_label="Gokbey DCC",
            dcc_template_name="gokbey_dcc_template",
            mail_template_name="gokbey_mail_template",
        ),
    }
)
