# Generated by Django 5.2 on 2026-01-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasenote',
            name='body_md',
        ),
        migrations.RemoveField(
            model_name='releasenote',
            name='note_type',
        ),
        migrations.CreateModel(
            name='ReleaseNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('feature', 'Feature'), ('fix', 'Fix'), ('breaking', 'Breaking'), ('info', 'Info'), ('security', 'Security')], max_length=16)),
                ('heading', models.CharField(blank=True, default='', max_length=200)),
                ('body_md', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('requires_ack', models.BooleanField(default=False)),
                ('release_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='releases.releasenote')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['release_note', 'item_type'], name='releases_re_release_4f2a77_idx')],
            },
        ),
    ]
