# Generated by Django 5.2 on 2026-01-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_remove_releasenote_body_md_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasenoteseen',
            name='client_version',
        ),
    ]
