# Generated by Django 5.2 on 2026-01-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_remove_releasenoteseen_client_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasenoteitem',
            name='requires_ack',
        ),
    ]
