# Generated by Django 5.2.15 on 2026-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0004_remove_releasenoteitem_requires_ack"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="releasenoteseen",
            options={"ordering": ["-seen_at", "user_id", "release_note_id"]},
        ),
    ]
